- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/sender_test.go
The `senderTest` struct had two different responsibilities
tucked into single data structure, violating the Single Responsibility
Principle and making it harder to read and write test code.
I have split the `senderTest` struct into two separate structs:
- `senderTest` used for testing the `sender` struct in `sender_test.go`,
- `exporterTest` used for testing the `sumologicexporter` struct in `exporter_test.go`.
> test(sumologicexporter): Refactor `senderTest` struct

- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
Add support for OTLP format for logs. This implementation doesn't respect HTTP restriction like message size. This is done such way due to simplicity and urgency of the solution
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp-request
https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto
> feat(sumologcexporter): add otlp logs support

- .github/workflows/dev_builds.yml
- .github/workflows/release_builds.yml
- otelcolbuilder/Makefile
Disable arm builds due to: https://github.com/golang/go/issues/46766
```
GOOS=linux   GOARCH=arm64 make build BINARY_NAME=otelcol-sumo-linux_arm64
make[1]: Entering directory '/home/runner/work/sumologic-otel-collector/sumologic-otel-collector/otelcolbuilder'
CGO_ENABLED=0 opentelemetry-collector-builder \
--go go \
--version "v0.0.2-8-g3f0a322966" \
--config .otelcol-builder.yaml \
--output-path ./cmd \
--name otelcol-sumo-linux_arm64
2021-06-16T13:36:17.427Z	INFO	cmd/root.go:99	OpenTelemetry Collector distribution builder	{"version": "dev", "date": "unknown"}
2021-06-16T13:36:17.427Z	INFO	cmd/root.go:115	Using config file	{"path": ".otelcol-builder.yaml"}
2021-06-16T13:36:17.428Z	INFO	builder/main.go:90	Sources created	{"path": "./cmd"}
2021-06-16T13:36:17.484Z	INFO	builder/main.go:126 …
```
> feat: skip builds for arm

- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/translate_metadata.go
- pkg/exporter/sumologicexporter/translate_metadata_test.go
User should be able to write it owns attributes (especially _source ones) and we shouldn't overwrite it
> sumologicexporter: do not overwrite attributes using metadata translation

- .golangci.yaml
- Makefile
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/sender_test.go
- pkg/extension/sumologicextension/extension_test.go
- pkg/processor/cascadingfilterprocessor/sampling/always_sample_test.go
- pkg/processor/k8sprocessor/client_test.go
- pkg/processor/k8sprocessor/doc.go
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/processor_test.go
- pkg/processor/sourceprocessor/source_processor.go
- pkg/receiver/telegrafreceiver/converter.go
Set conservative limit of line length to 185 (to not include too many changes in the repo).
> ci: add lll linter to golangci-lint config

- pkg/extension/sumologicextension/README.md
- pkg/extension/sumologicextension/api/register.go
- pkg/extension/sumologicextension/credentials.go
- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_test.go
- pkg/extension/sumologicextension/go.mod
Change mechanism of building encryption hash. Use combination of collector name, access ID and access key.
Signed-off-by: Patryk Matyjasek <pmatyjasek@sumologic.com>
> refactor: Change mechanism of building encryption hash

- pkg/extension/sumologicextension/README.md
- pkg/extension/sumologicextension/config.go
- pkg/extension/sumologicextension/credentials.go
- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_test.go
- pkg/extension/sumologicextension/factory.go
- pkg/extension/sumologicextension/factory_test.go
After first round of feedback it seems this setting is not obvious hence renaming it from `collector_credentials_path` to `collector_credentials_directory`
> refactor(sumologicextension): rename collector credentials path to directory

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- otelcolbuilder/Makefile
Builds for darwin need to be built with CGO_ENABLED set to 1 because some telegraf plugins that are used within the telegrafreceiver are implemented with CGO.
Example of this might be the cpu input plugin using gopsutil to the cpu stats.
https://github.com/shirou/gopsutil/blob/7ea80628/cpu/cpu_darwin_nocgo.go
https://github.com/shirou/gopsutil/blob/7ea80628/cpu/cpu_darwin.go
Without this user will see the following error from the telegraf agent:
```
2021/07/01 15:41:45 E! [inputs.cpu] Error in plugin: error getting CPU info: not implemented yet
```
---
Additionally don't cross compile darwin builds on linux but just use Mac runners on github. See this failed build for an example: https://github.com/SumoLogic/sumologic-otel-collector/runs/2963259368
> ci: set CGO_ENABLED to 1 on darwin builds

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
Due to a [beta toolchain bug](https://github.com/golang/go/issues/46080#issuecomment-864265977) don't use go1.17-beta1 for darwin builds, tests and release binaries (to release for all OSes using the same toolchain).
> ci: don't use go1.17-beta1 for builds

- pkg/exporter/sumologicexporter/compress.go
- pkg/exporter/sumologicexporter/compress_test.go
- pkg/exporter/sumologicexporter/go.mod
- pkg/exporter/sumologicexporter/go.sum
Use more performant optimized packages for compression: [github.com/klauspost/compress](https://github.com/klauspost/compress)
Benchmark results:
old:
```
goos: darwin
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/sumologicexporter
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkCompression
BenchmarkCompression/deflate
BenchmarkCompression/deflate-16                   203900             17899 ns/op           86267 B/op         20 allocs/op
BenchmarkCompression/gzip
BenchmarkCompression/gzip-16                      175705             20847 ns/op           87679 B/op         22 allocs/op
PASS
ok      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/sumologicexporter    31.009s
Execution time: 0h:00m:32s sec …
```
> refactor: use klauspost/compress for compression

- otelcolbuilder/.otelcol-builder.yaml
Add changes after upstream review
- fix splitFunc
- fix behavior if using `$` in regex
https://github.com/open-telemetry/opentelemetry-log-collection/pull/212/commits/fd4dbb8a26b6d14f7aa528a7eb0f57f020256d92
> fix: update log-collection dependency commit

- pkg/receiver/telegrafreceiver/receiver.go
Use context which is connected to `cancel` stored in the receiver struct so that calls to `Shutdown` actually cancel the context used for consuming metrics.
> fix(telegrafreceiver): use correct context when consuming metrics

- pkg/extension/sumologicextension/extension.go
`time.After` allocates a new timer on every call. Avoid that by reusing timer.
```go
package main
import (
"sync/atomic"
"testing"
"time"
)
const period = time.Nanosecond
func BenchmarkAfter(b *testing.B) {
for i := 0; i < b.N; i++ {
select {
case <-time.After(period):
}
}
}
func BenchmarkStopResetOnlyAfterTick(b *testing.B) {
timer := time.NewTimer(period)
for i := 0; i < b.N; i++ {
select {
case <-timer.C:
timer.Stop()
timer.Reset(period)
}
}
}
```
```
goos: darwin
goarch: amd64
pkg: timer
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkAfter
BenchmarkAfter-16                                4462508               790.0 ns/op           200 B/op          3 allocs/op
BenchmarkStopResetOnlyAfterTick
BenchmarkStopResetOnlyAfterTick-16               6640293               550.2 ns/op …
```
> sumologicextension: don't allocate timer on every heartbeat

- pkg/receiver/telegrafreceiver/converter.go
- pkg/receiver/telegrafreceiver/converter_test.go
- pkg/receiver/telegrafreceiver/metric_opt.go
~~This will allow something like this:~~
```yaml
processors:
metricstransform:
transforms:
- include: Net_.*
match_type: regexp
action: update
operations:
- action: update_label
label: interface
new_label: Interface
```
~~to work.~~
**EDIT**: Let's leave the functionality as is (i.e. retain copying the telegraf tags to resource attributes) but let's stick to the refactor that has been done in this PR to allow easier changes in code in the future and to decrease code duplication related to metric translation.
> refactor(telegrafreceiver): refactor

- pkg/exporter/sumologicexporter/exporter.go
Setting `auth: null`, or `auth.authenticator: null` in configiuration doesn't clear the authenticator configuration. In order to that we have to do it in code
> fix(sumologicexporter): do not use sumologic extension if endpoint is set

- otelcolbuilder/.otelcol-builder.yaml
Use https://github.com/SumoLogic/telegraf/releases/tag/v1.19.0-sumo-2 in order to add carbon2 parser
> chore: bump telegraf to v1.19.0-sumo-2 to add carbon2 parser

- pkg/processor/k8sprocessor/doc.go
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
- pkg/processor/k8sprocessor/pod_association.go
- pkg/processor/k8sprocessor/processor.go
- pkg/processor/k8sprocessor/processor_test.go
sync with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4310 ba01b0758
plus minor fixes in `doc.go`
> feat(k8sprocessor): support metadata enrichment for pod.namespace identifier

- docs/Configuration.md
This is to bring order to the configuration docs: Every extension, receiver, processor, exporter should have its own separate configuration section.
> docs(extensions): Create separate section for sumologicextension

- pkg/extension/sumologicextension/README.md
- pkg/extension/sumologicextension/config.go
- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_test.go
- pkg/extension/sumologicextension/factory.go
- pkg/extension/sumologicextension/factory_test.go
- pkg/extension/sumologicextension/go.mod
```
vagrant@sumologic-otel-collector:/sumologic/otelcolbuilder$ make build && ./cmd/otelcol-sumo --config /sumologic/tmp/config.yaml
CGO_ENABLED=0 opentelemetry-collector-builder \
--go go \
--version "v0.0.18-1-g61795eede9" \
--config .otelcol-builder.yaml \
--output-path ./cmd \
--name otelcol-sumo
2021-08-10T08:27:52.255Z        INFO    cmd/root.go:99  OpenTelemetry Collector distribution builder    {"version": "0.29.0", "date": "2021-06-25T14:36:50Z"}
2021-08-10T08:27:52.256Z        INFO    cmd/root.go:115 Using config file       {"path": ".otelcol-builder.yaml"}
2021-08-10T08:27:52.256Z        INFO    builder/main.go:55      You're building a distribution with non-aligned version of the builder. Compilation may fail due to API changes. Please upgrade your builder or API …
```
> Add backoff mechanism to registration call

- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/sender.go
setting it to true indicates that backend will be responsible for timestamp parsing
> feat(sumologicexporter): add clear_logs_timestamp option

- pkg/extension/sumologicextension/extension.go
Instead of using `time.Sleep()` use `time.NewTimer()`'s channel so that we can listen on it and on `context.Done()`
> sumologicextension: allow cancelling collector registration with context

- examples/ansible/install_sumologic_otel_collector.yaml
- examples/puppet/modules/install_otel_collector/manifests/init.pp
This change is done due to security good practice, as config can contain sensitive data
> fix(ansible): strip read permission for config for others

- Dockerfile
- Dockerfile_dev
- Dockerfile_local
- Makefile
This is to avoid:
```
2021-09-03T12:23:13.005Z  error   sumologicextension@v0.33.0/extension.go:225     Unable to store collector credentials   {"kind": "extension", "name": "sumologic", "error": "mkdir /.sumologic-otel-collector: permission denied"}
```
> fix: set HOME in container image and assign proper ownership to it

- pkg/exporter/sumologicexporter/carbon_formatter.go
- pkg/exporter/sumologicexporter/fields.go
- pkg/exporter/sumologicexporter/graphite_formatter.go
- pkg/exporter/sumologicexporter/prometheus_formatter.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/source_format.go
It was removed in https://github.com/open-telemetry/opentelemetry-collector/pull/3953 and it's already not available in https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.35.0
> chore: don't use deprecated pdata.AttributeValueToString

- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/prometheus_formatter.go
- pkg/exporter/sumologicexporter/prometheus_formatter_test.go
- pkg/exporter/sumologicexporter/sender_test.go
Allow `.` and `/` for prometheus key
> feat(sumologicexporter): allows `.`, `/`, `:` and `_` for prometheus key

- pkg/exporter/sumologicexporter/prometheus_formatter.go
- pkg/exporter/sumologicexporter/prometheus_formatter_test.go
We need it for compatibility with fluentd. If metadata label contains `-` it should be send as `-` instead of `_`
> feat(sumologicexporter): add support for `-` to prometheus format

- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/translate_attributes.go
- pkg/exporter/sumologicexporter/translate_attributes_test.go
This will help in cases where some want to use `_sourceName` in source template which until now rendered `undefined`.
> fix(sourceprocessor): don't prevent using attributes from Sumo schema in source templates

- otelcolbuilder/.otelcol-builder.yaml
This PR enables `strict` and `regexp` filtering of logs based on resource attributes using filterprocessor.
ref: https://github.com/pmalek-sumo/opentelemetry-collector-contrib/commit/6643765789daf85c51150b5de8bb64a82d9c52e0
related PR upstream that will introduce this when merged: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5237
> feat(filterprocessor): enable log filtering

- pkg/processor/sourceprocessor/attribute_filler.go
- pkg/processor/sourceprocessor/source_processor.go
- pkg/processor/sourceprocessor/source_processor_test.go
It seems that using `source_host_key` in source processor didn't work at all.
This PR adds the missing functionality and some tests for that.
> fix(sourceprocessor): fix source_host_key feature

- pkg/processor/sourceprocessor/README.md
- pkg/processor/sourceprocessor/source_processor.go
Instead of relying on this behavior, use e.g. attributes processor in the pipeline.
> sourceprocessor: don't try to add host for systemd related records

- pkg/processor/k8sprocessor/config.go
- pkg/processor/sourceprocessor/README.md
- pkg/processor/sourceprocessor/config_test.go
- pkg/processor/sourceprocessor/factory.go
- pkg/processor/sourceprocessor/source_processor_test.go
docs(sourceprocessor): clarify pod_name behavior 
refactor(sourceprocessor)!: change default key names to fit k8s and this repo convention
change defaukt keys to be compatible with k8sprocessor
> clarify pod_name behavior and change default key names to fit convention

- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
- pkg/processor/k8sprocessor/kube/kube.go
Fix: namespace does not need to be in extracted metadata when there is following configuration
```
pod_association:
- from: build_hostname
```
without this fix it is required to this section to configuration:
```
extract:
metadata:
- namespace
```
related to: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1762
> fix(k8sprocessor): namespace does not need to be in extracted metadata

- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
To prevent sending `null` logs check if the body is not empty before attaching it like in the attached screenshot:
> fix(sumologicexporter): don't send null logs

- pkg/processor/sourceprocessor/README.md
- pkg/processor/sourceprocessor/config.go
- pkg/processor/sourceprocessor/config_test.go
- pkg/processor/sourceprocessor/factory.go
- pkg/processor/sourceprocessor/source_processor.go
- pkg/processor/sourceprocessor/testdata/config.yaml
It doesn't do anything.
Contrary to what the docs claim, the `_source` tag is not set by the Source processor.
> docs(sourceprocessor): remove `source` configuration option

- README.md
- docs/Configuration.md
e.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sprocessor doesn't exist anymore because of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5384 (changing name from `k8sprocessor` to `k8sattributesprocessor` )
> fix(doc): fix outdated otc-contrib links

- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/fields.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
- pkg/exporter/sumologicexporter/translate_attributes.go
- pkg/exporter/sumologicexporter/translate_attributes_test.go
- Stop rewriting structures in place
- Fix duplicating translated metadata in X-Sumo-Fields and Json format
> refactor(sumologicexporter): don't change attributes in place when translating

- pkg/processor/sourceprocessor/README.md
- pkg/processor/sourceprocessor/attribute_filler.go
- pkg/processor/sourceprocessor/config.go
- pkg/processor/sourceprocessor/config_test.go
- pkg/processor/sourceprocessor/factory.go
- pkg/processor/sourceprocessor/source_processor.go
- pkg/processor/sourceprocessor/source_processor_test.go
- pkg/processor/sourceprocessor/testdata/config.yaml
This change replaces `source_host_key` configuration option with `source_host` option.
This is for consistency, to allow templating of source host field in the same way that source name and source category fields can be templated.
BREAKING CHANGE: `source_host_key` option is removed in favor of `source_host` option.
To upgrade, take the value of `source_host_key`, surround it with `'%{` and `}'`, and put it in `source_host` option.
For example: `source_host_key: k8s.pod.hostname` should be changed to `source_host: '%{k8s.pod.hostname}'`
> feat(sourceprocessor)!: allow templating of source host field

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- Makefile
- otelcolbuilder/Makefile
In order to make sure the project is built with proper builder version let's check it every time the collector is built.
> ci: check builder version when building collector

- otelcolbuilder/.otelcol-builder.yaml
The PR in question: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5676 has been merged upstream and released already as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.38.0 specifically in this commit: https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/1ac25f9e94c34c3a708a17e8d4d0af3a65133521
> fluentforwardreceiver: remove replace from builder config since changes were merged upstream

- pkg/extension/sumologicextension/extension.go
Before:
```
Error: cannot start exporters: failed to create HTTP Client: requested authenticator is not a client authenticator
2021/11/17 11:58:54 collector server run finished with error: cannot start exporters: failed to create HTTP Client: requested authenticator is not a client authenticator
```
After:
```
2021-11-17T12:00:40.633+0100	info	service/collector.go:132	Everything is ready. Begin running and processing data.
2021-11-17T12:00:40.876+0100	debug	sumologicextension@v0.38.0/extension.go:425	Heartbeat sent	{"kind": "extension", "name": "sumologic/otc-extension", "collector_name": "Collector_Test_Otc-ubuntu1804LTS-1637162421020", "collector_id": "0000000006530DFC"}
```
> Add missing interface method for configauth.ClientAuthenticator

- README.md
- otelcolbuilder/.otelcol-builder.yaml
- pkg/extension/sumologicextension/go.mod
This adds almost all receiver and processor components from OpenTelemetry Collector Contrib.
It also lists otlpexporter and otlphttpexporter as available (since they are part of core and could be useful for pipelining collectors)
Additionally, it bumps the core version to v0.38.0 (which includes a quite important fix for K8s tracing workloads)
There's no documentation provided for the newly added components. We can discuss if it should be provided later or skipped altogether (keeping our distro docs in sync with upstream for all components might require significant amount of work and maybe we should just point to upstream docs)
The components add ~6 MiB (or 4%) extra to the macOS binary
```
-rwxr-xr-x   1 pmaciolek  staff  148868536 Nov 12 12:13 otelcol-sumo
-rwxr-xr-x   1 pmaciolek …
```
> Include additional upstream OTC components

- .github/workflows/pull_requests.yml
This reverts commit 8c7fc3c19090bcd7a54d7d4a047530d472a2aa55.
Seems this has caused the issue of not buildable container: here's a CI run with tj-actions reverted to v11 which passed: https://github.com/SumoLogic/sumologic-otel-collector/runs/4550802501?check_suite_focus=true
For completeness here's a failed CI run: https://github.com/SumoLogic/sumologic-otel-collector/runs/4550599183?check_suite_focus=true
> Revert "chore(deps): bump tj-actions/changed-files from 11 to 12 (#360)"

- pkg/processor/k8sprocessor/README.md
- pkg/processor/k8sprocessor/client_test.go
- pkg/processor/k8sprocessor/config.go
- pkg/processor/k8sprocessor/config_test.go
- pkg/processor/k8sprocessor/factory.go
- pkg/processor/k8sprocessor/go.mod
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
- pkg/processor/k8sprocessor/kube/kube.go
- pkg/processor/k8sprocessor/options.go
- pkg/processor/k8sprocessor/options_test.go
- pkg/processor/k8sprocessor/processor.go
- pkg/processor/k8sprocessor/processor_test.go
- pkg/processor/k8sprocessor/testdata/config.yaml
This PR retrofits upstream PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3520
> feat(k8sprocessor): add ignored pod names as config parameter

- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
exemplar log entry:
```
2021-12-17T11:45:09.037Z        debug   sumologicexporter@v0.40.0/sender.go:154 Sending data    {"kind": "exporter", "name": "sumologic/containers", "headers": {"Content-Encoding":["gzip"],"Content-Type":["application/x-www-form-urlencoded"],"X-Sumo-Category":["kubernetes/sumologic/collection/sumologic/otelcol/logs"],"X-Sumo-Client":["otelcol"],"X-Sumo-Fields":["_collector=pmalek-kubernetes-vagrant-2, container=otelcol, host=sumologic-kubernetes-collection, k8s.container.id=bb0f1137b251ddae622df6d54161204a4b27275d635715b25232320bbdf1967a, k8s.pod.id=8a1767d5-f4a2-410f-ac77-4a3465222e8f, k8s.pod.pod_name=collection-sumologic-otelcol-logs, namespace=sumologic, namespace_labels_kubernetes.io/metadata.name=sumologic, node=sumologic-kubernetes-collection, …
```
> feat(sumologicexporter): add debug log with request headers

- otelcolbuilder/.otelcol-builder.yaml
Related tag: https://github.com/SumoLogic/telegraf/releases/tag/v1.20.4-sumo-1
Includes https://github.com/SumoLogic/telegraf/commit/7efb4e4c9205c64f4e2988552ac764f1c5cd5b9e which bumps to:
* `github.com/opencontainers/image-spec@v1.0.2`
* `github.com/containerd/containerd@v1.5.8`
which was mentioned by dependabot in security review
> chore(deps): bump telegraf to 1.20.4-sumo-1

- pkg/exporter/sumologicexporter/go.mod
- pkg/extension/sumologicextension/go.mod
With this change our plugins (including sumologicexporter and sumologicextension) will be importable. 
I've created https://github.com/SumoLogic/sumologic-otel-collector/issues/372 in order to figure out how to keep the dependency in sync.
> fix: fix modules so that they are importable

- otelcolbuilder/Makefile
Due to [recent changes in tags that are being pushed to this repo](https://github.com/SumoLogic/sumologic-otel-collector/pull/370) we need to be more specific w.r.t to the tags that we can match when calling `git describe` to get the version string that we embed in the binary.
This is to prevent getting a version string like:
```
pkg/processor/metricfrequencyprocessor/v0.0.44-beta.0-1-geb02b42d1d
```
> fix: add match glob pattern to git describe

- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/owner.go
- pkg/processor/k8sprocessor/kube/owner_test.go
> NOTE:
> There is a problematic aspect of those tests which is in detail described in the comment in `owner_test.go`. One can verify the problem by running e.g. `while go test -v -count 100 -race -run Test_Owner ./kube/...; do ; done` and observing that the tests sometimes fail.
The primary concern of this PR is below mentioned data race.
At the same time add some unit tests which would run the changed code.
```
==================
WARNING: DATA RACE
Write at 0x00c00127a420 by goroutine 44:
runtime.mapdelete_faststr()
runtime/map_faststr.go:300 +0x0
github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sprocessor/kube.(*WatchClient).deleteLoop()
github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sprocessor@v0.41.0/kube/client.go:203 +0x564 …
```
> fix(k8sprocessor): fix data race in k8sprocessor and some some tests

- pkg/processor/k8sprocessor/kube/client.go
When there's no services found for a pod, do not include an empty service label.
> fix(k8sprocessor): do not include empty service label

- pkg/processor/k8sprocessor/client_test.go
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
- pkg/processor/k8sprocessor/kube/kube.go
- pkg/processor/k8sprocessor/kube/owner_test.go
- pkg/processor/k8sprocessor/processor.go
- pkg/processor/k8sprocessor/processor_test.go
There was a "memory leak" in `k8sprocessor` caused by not deleting a pod from cache in `forgetPod` under the following ID:
```go
fmt.Sprintf("%s.%s", p.GetName(), p.GetNamespace())
```
This PR fixes it and adds test to ensure this. In order to do so delete interval and grace period (both use in the delete loop) needed to be made configurable (not to wait 30s + 120s in tests).
> fix(k8sprocessor): delete pod entries for all corresponding IDs

- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/fake_owner.go
- pkg/processor/k8sprocessor/kube/owner.go
- pkg/processor/k8sprocessor/kube/owner_test.go
It seems that k8sprocessor was enabling informers regardless whether the extraction rules for them were configured.
This caused unnecessary load on the processor and on some clusters e.g. k8s versions < 1.20 errors like:
```
E0117 09:57:48.400854       1 reflector.go:138] k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v1.CronJob: failed to list *v1.CronJob: the server could not find the requested resource
```
because the client was configured to watch event on resource that didn't exist on the cluster.
This PR addresses that.
> feat(k8sprocessor): only enable owner informers when configured

- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/fields.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
When a payload gets split due to `max_request_body_size` we shouldn't remove source related fields as they will be used by other requests yet to be sent.
This causes `undefined` source category, name and host being set.
> fix(sumologicexporter): don't remove fields after sending data

- pkg/extension/sumologicextension/config.go
- pkg/extension/sumologicextension/credentials/credentialsstore_localfs.go
- pkg/extension/sumologicextension/credentials/credentialsstore_localfs_test.go
- pkg/extension/sumologicextension/credentials/encrypt.go
- pkg/extension/sumologicextension/credentials/store.go
- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_test.go
- pkg/extension/sumologicextension/factory.go
- pkg/extension/sumologicextension/factory_test.go
Refactor sumologicextension's credentialsstore so that it's put in a separate package.
This way it's more separated from the extension's code. And will be easier to reason about and easier to extend.
> refactor(sumologicextension): refactor credentialsstore

- otelcolbuilder/.otelcol-builder.yaml
This name for instance is used in help.
> fix: specify otelcol's binary name

- Vagrantfile
Vbox 6.1.28 restricts the IP addresses permitted in host-only networks
to 192.168.56.0/21. This can be changed via vbox config, but we don't
care what our guest IP is, so changing that instead is simpler.
See: https://www.virtualbox.org/manual/ch06.html#network_hostonly
> chore(vagrant): use IP in allowed range

- pkg/exporter/sumologicexporter/graphite_formatter.go
- pkg/exporter/sumologicexporter/graphite_formatter_test.go
Unfortunately Graphite doesn't have a proper spec for what is and isn't allowed in a metric path. For now I've explicitly disallowed newlines, which definitely aren't. I've tested some special characters with the Sumo backend itself, and it seems to accept them just fine, so I don't think we should be any different here.
As a point of reference, carbon-relay-ng has three different validation modes for this: https://github.com/grafana/carbon-relay-ng/blob/master/docs/validation.md#message-validation
> fix(sumologicexporter): escape newlines for Graphite metrics

- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_test.go
This PR addresses the problem of Sumo API returning 401 during collector's runtime in which case data stops being sent due to collector not being able to get authorized.
With this PR the collector will detect that (via 401 returned on heartbeat request), trigger re-registration and then `sumologicexporter` will reconfigure as well if it detects 401 in response to sending data.
Exemplar log from re-registration process:
```
2022-02-22T14:42:25.378+0100    debug   sumologicexporter@v0.44.0/sender.go:156 Sending data    {"kind": "exporter", "name": "sumologic/1", "pipeline": "metrics", "headers": {"Content-Encoding":["gzip"],"Content-Type":["application/x-protobuf"],"X-Sumo-Client":["otelcol"],"X-Sumo-Host":["pmalek_source_host"],"X-Sumo-Name":["pmalek_source_name"]}} …
```
> feat(sumologicextension): re-register collector on HTTP Unauthorized

- pkg/exporter/sumologicexporter/carbon_formatter.go
- pkg/exporter/sumologicexporter/carbon_formatter_test.go
We've already been escaping \n here, as we should. I added \r and a test for this behaviour.
> fix(sumologicexporter): escape \r in Carbon metrics

- pkg/exporter/sumologicexporter/prometheus_formatter.go
- pkg/exporter/sumologicexporter/prometheus_formatter_test.go
Newlines weren't correctly escaped in Prometheus metric names and label values.
> fix(sumoexporter): Prometheus newline sanitization

- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/fields.go
- pkg/exporter/sumologicexporter/go.mod
The `fields.string()` method is not good for comparisons because it ignores the `_sourceName` attribute.
Refs: SUMO-187202
> fix(sumologicexporter): fix batching logs from different files

- otelcolbuilder/.otelcol-builder.yaml
- pkg/receiver/telegrafreceiver/go.mod
- pkg/receiver/telegrafreceiver/go.sum
- pkg/receiver/telegrafreceiver/receiver.go
- pkg/receiver/telegrafreceiver/receiver_test.go
It was possible to create panics in Telegraf agent by closing the channel before the input plugin is done closing. We fix this in two ways:
1. let Telegraf agent close the channel on its own, and wait for it to do so before shutting down the receiver
2. upgrade to a new Telegraf version where the http plugin closes more gracefully, see the change here: https://github.com/SumoLogic/telegraf/pull/36
We also add a simple test for receiver start and shutdown.
> fix(telegrafreceiver): shutdown Telegraf agent gracefully

- .github/workflows/release_builds.yml
In order to make the binary included in the release signed we need to add it to pipeline artifacts after signing finishes.
> ci-add-darwin-binary-to-artifacts-after-signing

- .github/workflows/release_builds.yml
This will fix builds like this: https://github.com/SumoLogic/sumologic-otel-collector/runs/5478153020?check_suite_focus=true where CI expects an artifact without the version included in the filename.
> fix(ci): release job should store artifacts without version

- .github/workflows/release_builds.yml
Require darwin build to succeed to prevent pushing container images when darwin build fails.
> fix(ci): prevent pushing container images when darwin build fails

- docs/Configuration.md
We don't want to document each upstream component we incorporate in Sumo distro - we would be duplicating those components' upstream documentation.
Instead, we want to describe the configuration that is needed to achieve a specific goal, like for example collecting logs from files.
> docs(configuration): describe use cases instead of components

- README.md
This follows #463.
Added OTLP receiver, batch and memory_limiter processors.
Removed db_storage extension as we don't actually include it.
Fixed alphabetical ordering.
> docs(readme): add missing components

- docs/Configuration.md
This solution is not perfect but there is not so many alternatives
> docs(configuration): add example for keeping prometheus format with OTLP

- .github/workflows/release_builds.yml
Example of a failed CI run: https://github.com/SumoLogic/sumologic-otel-collector/runs/5625676154?check_suite_focus=true
> fix(ci): install gon by curl not via broken brew tap

- .circleci/config.yml
- .golangci.yaml
- pkg/Makefile.Common
- pkg/test/timestamp_test.go
Update to go 1.18 missed a few things. This PR updates the remaining go 1.17 config to 1.18
> chore: bump go version to 1.18

- ci/check_uniform_dependencies.sh
We haven't been using github.com/SumoLogic/opentelemetry-collector
since #201 (v0.0.22-beta.0).
> ci(check-uniform-dependencies): don't check for non-existent dependency

- Makefile
Related release: https://github.com/golangci/golangci-lint/releases/tag/v1.45.2
> chore(ci): bump golangci-lint to 1.45.2

- pkg/processor/k8sprocessor/pod_association.go
- pkg/processor/k8sprocessor/processor_test.go
Backports https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7077.
> fix(k8sprocessor): parse IP out of net.Addr to correctly tag k8s.pod.ip

- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/go.mod
- pkg/exporter/sumologicexporter/go.sum
- pkg/exporter/sumologicexporter/internal/observability/observability.go
- pkg/exporter/sumologicexporter/internal/observability/observability_test.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
Generated metrics
```
otelcol_sumologic_requests_bytes{endpoint="http://localhost:3000",pipeline="metrics",service_instance_id="00e0fe04-5899-4b4b-9e4d-c2dee53af447",service_version="latest",status_code="0"} 297107
otelcol_sumologic_requests_bytes{endpoint="http://localhost:3000",pipeline="metrics",service_instance_id="00e0fe04-5899-4b4b-9e4d-c2dee53af447",service_version="latest",status_code="200"} 1.727096e+06
otelcol_sumologic_requests_duration{endpoint="http://localhost:3000",pipeline="metrics",service_instance_id="00e0fe04-5899-4b4b-9e4d-c2dee53af447",service_version="latest",status_code="0"} 0
otelcol_sumologic_requests_duration{endpoint="http://localhost:3000",pipeline="metrics",service_instance_id="00e0fe04-5899-4b4b-9e4d-c2dee5 …
```
> feat(exporter/sumologic): add metrics for HTTP requests

- otelcolbuilder/cmd/testdata/telegrafreceiver_sumologicexporter_endpoint.yaml
- pkg/receiver/telegrafreceiver/README.md
- pkg/receiver/telegrafreceiver/config.go
- pkg/receiver/telegrafreceiver/factory.go
- pkg/receiver/telegrafreceiver/go.mod
- pkg/receiver/telegrafreceiver/go.sum
- pkg/receiver/telegrafreceiver/receiver.go
- pkg/receiver/telegrafreceiver/receiver_test.go
Retry recoverable errors from the rest of the pipeline using a simple constant backoff strategy. I've made the backoff configurable primarily to make testing easier, but users shouldn't really touch these values in most circumstances, which is why I'm not including them in the README.
> fix(telegrafreceiver): retry recoverable errors

- otelcolbuilder/.otelcol-builder.yaml
- pkg/receiver/telegrafreceiver/go.mod
- pkg/receiver/telegrafreceiver/go.sum
This version contains a backpressure fix to http_listener_v2: https://github.com/SumoLogic/telegraf/pull/38.
> chore(telegrafreceiver): update telegraf to v1.22.0-sumo-2

- Makefile
https://stackoverflow.com/a/589300
Fixes:
```
➜  ~ cd projects/sumologic-otel-collector 
➜  sumologic-otel-collector git:(main) ✗ git reset --hard
HEAD is now at 1e0f157 docs(known-issues): describe filelog multiline issue
➜  sumologic-otel-collector git:(main) ✗ export TAG=v0.0.59-beta.1 ; make add-tag 
Adding tag v0.0.59-beta.1
/bin/sh: 2: Bad substitution
make: *** [Makefile:126: add-tag] Error 2
```
> chore(Makefile): use bash as default shell

- pkg/processor/k8sprocessor/kube/client_test.go
- pkg/processor/k8sprocessor/kube/owner.go
- pkg/processor/k8sprocessor/kube/owner_test.go
> fix(k8sprocessor): fix metadata dependencies

- pkg/exporter/sumologicexporter/fields.go
- pkg/exporter/sumologicexporter/fields_test.go
Use byte slices instead of strings where possible and modify a "stringified field byte slice" in place to prevent unnecessary copies.
Additionally short circuit in `fields.equals()` when attribute maps have different length to prevent using `cmp` for comparison (which is relatively expensive).
```
$ go test -v -count 1 -run ^$ -bench BenchmarkFields -benchmem -count 1 . > old.txt
$ gco -
Previous HEAD position was 86d1d22 tests(sumologicexporter): add fields stringification benchmark
Switched to branch 'optimize-fields'
$ go test -v -count 1 -run ^$ -bench BenchmarkFields -benchmem -count 1 . > new.txt
$ benchcmp old.txt new.txt
benchcmp is deprecated in favor of benchstat: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
benchmark              old ns/op     new ns/op     delta …
```
> refactor(sumologicexporter): optimize fields stringification

- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/config_test.go
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/sender_test.go
This PR tries to address unnecessary creation of data compressor instances on every `push(Logs|Metrics|Traces)` invocation using `sync.Pool`
```
$ go test -v -count 1 -run ^$ -bench Benchmark_ExporterPushLogs -benchmem -count 5 -benchtime 200x . > old.txt
$ git(5651893) gco -
Previous HEAD position was 5651893 tests(sumologicexporter): add exporter logs sending benchmark
Switched to branch 'optimize-compression'
$ go test -v -count 1 -run ^$ -bench Benchmark_ExporterPushLogs -benchmem -count 5 -benchtime 200x . > new.txt
$ benchcmp old.txt new.txt
benchcmp is deprecated in favor of benchstat: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
benchmark                         old ns/op     new ns/op     delta
Benchmark_ExporterPushLogs-16     2396758       2079249       -13.25% …
```
> refactor(sumologicexporter): optimize compressor using sync.Pool

- ci/build-push-multiplatform.sh
It seems that sometimes runner can't connect to docker daemon (that's an assumption since we capture `docker buildx ..`'s output in `| grep ...` pipe).
This PR adds a loop that ensures we can connect to docker daemon and it also reuses the once used output of `docker buildx ls`.
It also adds a debug print of the very same output instead of issuing the command again to ensure what we get printed in CI logs is what actually caused the job to fail.
Example of a failed CI job: https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/2090188603
> fix(ci): ensure we can connect to docker daemon when building images

- .github/workflows/release_builds.yml
| - | - |
|-----------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| allowUpdates          | An optional flag which indicates if we should update a release if it already exists. Defaults to false.                                                                         |
| omitBody              | Indicates if the release body should be omitted.                                                                                                                                |
| omitBodyDuringUpdate  | Indicates if the release body should be omitted during updates. The body will still be applied for newly created releases. This will preserve the …
> ci: allow release updates

- .yamllint.yaml
Some of the lines are naturally long and can't easily be broken up. This makes the check pass without warnings again.
> chore: increase max line length for yamllint

- README.md
Let's use the name used in the press release:
Sumo Logic OpenTelemetry Distro Collector.
> docs(readme): update repo title

- .golangci.yaml
- pkg/exporter/sumologicexporter/fields.go
- pkg/exporter/sumologicexporter/go.mod
- pkg/exporter/sumologicexporter/go.sum
This PR uses generic slice sorting algorithm and saves yet another allocation in `fields.string()`.
Related article: https://eli.thegreenplace.net/2022/faster-sorting-with-go-generics/
```
benchcmp old.txt new.txt
benchcmp is deprecated in favor of benchstat: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
benchmark              old ns/op     new ns/op     delta
BenchmarkFields-16     646           618           -4.32%
BenchmarkFields-16     642           603           -6.03%
BenchmarkFields-16     636           614           -3.35%
BenchmarkFields-16     640           616           -3.72%
BenchmarkFields-16     648           612           -5.56%
benchmark              old allocs     new allocs     delta
BenchmarkFields-16     11             10             -9.09%
BenchmarkFields-16 …
```
> refactor(sumologicexporter): use golang.org/x/exp/slices for sorting fields

- pkg/exporter/sumologicexporter/prometheus_formatter.go
- pkg/exporter/sumologicexporter/prometheus_formatter_test.go
```
$ benchcmp main.txt pr.txt
benchmark                                          old ns/op     new ns/op     delta
Benchmark_PrometheusFormatter_Metric2String-16     66901         53862         -19.49%
Benchmark_PrometheusFormatter_Metric2String-16     65607         53773         -18.04%
Benchmark_PrometheusFormatter_Metric2String-16     65205         54047         -17.11%
benchmark                                          old allocs     new allocs     delta
Benchmark_PrometheusFormatter_Metric2String-16     696            512            -26.44%
Benchmark_PrometheusFormatter_Metric2String-16     696            512            -26.44%
Benchmark_PrometheusFormatter_Metric2String-16     696            512            -26.44%
benchmark                                          old bytes     new …
```
> refactor(sumologicextension): use bytes slices and strings.Builder to decrease allocations

- CHANGELOG.md
- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/fields.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
- pkg/exporter/sumologicexporter/source_format.go
This PR aims at treating OTLP resource level attributes as [fields](https://help.sumologic.com/Manage/Fields).
It also simplifies the OTLP flows a bit by removing the unnecessary batching from their logic.
> fix(sumologicexporter): treat resource attributes as fields for otlp

- .github/workflows/changelog.yaml
This seems to work nicely in contrib: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/changelog.yml
> ci: add a check for changelog changes

- CHANGELOG.md
- Makefile
Fixing the changelog after forgetting to update it while releasing 0.48.0. Added some missing items while at it, and have markdownlint run on all *.md files in the repo, which now also includes CHANGELOG.md and CONTRIBUTING.md.
> docs: fix changelog

- pkg/tools/udpdemux/Makefile
- pkg/tools/udpdemux/README.md
- pkg/tools/udpdemux/go.mod
- pkg/tools/udpdemux/main.go
This tool should serve a temporary purpose of fanning out UDP traffic to multiple collectors so that we can verify we are processing the data in them in the similar/the same way.
> feat: add udpdemux tool

- CHANGELOG.md
- pkg/processor/cascadingfilterprocessor/metrics.go
- pkg/processor/cascadingfilterprocessor/processor.go
- pkg/processor/cascadingfilterprocessor/processor_test.go
When two cascading filter processor instances were running on one collector, the metrics values were overridden. Adding the instance_name tag fixes this issue
> fix(cascadingfilterprocessor): prevent overriding metrics in cascading filter processor - add processor tag

- CHANGELOG.md
- docs/Upgrading.md
Describe the breaking change to `opentelemetry-log-collection` in the changelog.
> docs: add breaking change description to changelog

- CHANGELOG.md
- otelcolbuilder/.otelcol-builder.yaml
- pkg/receiver/telegrafreceiver/go.mod
- pkg/receiver/telegrafreceiver/go.sum
This is only to restore the `socket_receiver` plugin as seen in this change: https://github.com/SumoLogic/telegraf/pull/39.
Also fixed a missing link in the changelog.
> chore: bump Telegraf to v1.22.0-sumo-3

- Makefile
When cloning a repo, the remote is named `origin` by default, not `upstream`.
> chore(makefile): use default remote name `origin` in `push-tag` target

- CHANGELOG.md
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
#549 changed log and metrics exporting to send each Resource in a separate batch. This behaviour is correct for logs, whose metadata is passed via a X-Sumo-Fields http header, but is wasteful for metrics, where it's passed in the body. This change makes the exporter send all metrics in a batch in a single request, unless the source headers are different.
To achieve this we change several internal interfaces:
* `sendNonOtlpMetrics` now takes and returns a `pmetric.Metrics`, like the tracing equivalent
* the metrics sender now operates on resources, instead of individual datapoints
* removed some superfluous error handling around string builders
> fix(sumologicexporter): batch metrics if source headers match

- CHANGELOG.md
- pkg/processor/cascadingfilterprocessor/processor.go
- pkg/processor/cascadingfilterprocessor/processor_test.go
This makes sure that `sampling.rule` attr is attached only when trace accept filters are defined only. 
Previously, when drop trace filters were specified the `sampling.rule=filtered` attribute was attached, which in lack of probabilistic filter caused Trace2Metrics calculations create no actual metrics
> fix(cascadingfilterprocessor): do not attach sampling.rule attribute if trace accept rules are not specified

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- CHANGELOG.md
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/fields.go
- pkg/exporter/sumologicexporter/go.mod
- pkg/exporter/sumologicexporter/go.sum
otelcol must be built also on [Go+BoringCrypto](https://github.com/golang/go/blob/dev.boringcrypto.go1.18/README.boringcrypto.md). 
currently Go+BoringCrypto  for go 1.18 is not available so we must restore support for go 1.17, list of available releases: https://github.com/golang/go/blob/dev.boringcrypto.go1.18/misc/boring/RELEASES.
CI pipelines will be adjusted for building otelcol on [Go+BoringCrypto](https://github.com/golang/go/blob/dev.boringcrypto.go1.18/README.boringcrypto.md) in another pull request.
This PR contains necessary changes in the code to support go 1.17 with go version change in CI pipelines to prove that it is building on go 1.17.
This PR reverts some changes introduced in:
- https://github.com/SumoLogic/sumologic-otel-collector/pull/519
- …
> Restore support for go 1.17

- CHANGELOG.md
- docs/Configuration.md
- otelcolbuilder/cmd/testdata/filelog_reallife_complicated_sumologicexporter.yaml
- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/translate_attributes.go
This is to match the change of the attribute name created by Filelog receiver
that was made in upstream OTC contrib v0.49.0.
> feat(sumologicexporter)!: attribute translation: change `file.path.resolved` to `log.file.path_resolved`

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- CHANGELOG.md
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/fields.go
- pkg/exporter/sumologicexporter/go.mod
- pkg/exporter/sumologicexporter/go.sum
Reverts SumoLogic/sumologic-otel-collector#574
Found release of Go+BoringCrypto for go 1.18 https://github.com/golang/go/blob/e52cc9d0fd63077f67a7fe5edd272c0db432307e/misc/boring/RELEASES#L188-L189
> Revert "Restore support for go 1.17"

- CHANGELOG.md
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
Informers are a convenient mechanism for maintaining an eventually-consistent local cache of Kubernetes objects. One of the problems with them used to be that it was difficult to customize the object data stored in the cache, leading to unnecessarily large memory usage even when the client only cared about a small subset of the data. `client-go` 0.23.0 added a mechanism to do this, where it's possible to provide the informer with a transform function applied to the object before it's stored and event handlers are fired.
We supply a transform function to only retain the Pod data we use in our cache. Truthfully, we could get rid of all of it, as we keep the computed metadata in a separate data structure, but that would require implementing a custom Store. The transform function approach is …
> fix(k8sprocessor): store only necessary Pod data

- CHANGELOG.md
- README.md
- otelcolbuilder/.otelcol-builder.yaml
* Addresses: https://github.com/SumoLogic/sumologic-otel-collector/issues/595
* [Cumulative To Delta Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/cumulativetodeltaprocessor)
* My use case of this is that not all vendors support Cumulative metrics and being able to use this processor to convert them to Delta would be incredibly helpful.
> Add CumulativeToDelta Processor

- CHANGELOG.md
- README.md
- otelcolbuilder/.otelcol-builder.yaml
> feat: add logstransformprocessor from upstream

- CHANGELOG.md
- pkg/processor/cascadingfilterprocessor/long_running_test.go
- pkg/processor/cascadingfilterprocessor/processor.go
This fixes the case with increased memory consumption when spans for traces where decision was already made are observed
> fix(cascading_filter): fix leak on traces where decision was made

- pkg/processor/cascadingfilterprocessor/long_running_test.go
- pkg/processor/cascadingfilterprocessor/processor.go
Backport a fix for cascading filter memory leak: https://github.com/SumoLogic/sumologic-otel-collector/pull/616
> backport: fix(cascading_filter): fix leak on traces where decision was made

- .github/workflows/release_builds.yml
- CHANGELOG.md
There's an infrastructure issue with signing the MacOS binaries.
Until it is resolved, let's release new versions without MacOS binaries.
> ci: disable MacOS builds while signing not possible

- .github/workflows/dev_builds.yml
- .github/workflows/release_builds.yml
to have `latest` image available as last image in ECR not `latest-fips`
> chore(ci): change order of pushing to ECR

- docs/release.md
We want to include in Sumo distro all the components that are included
in upstream otelcol and otelcol-contrib distros,
which is different from the list of components that exist in source code.
> docs(release): change source of upstream components

- CHANGELOG.md
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/sender.go
This change fixes a regression introduced in https://github.com/SumoLogic/sumologic-otel-collector/pull/536 that caused the metric name translations (the feature under the `translate_telegraf_attributes` setting) to not work when using the OTLP format.
This change refactors the code so that all modifications to metrics (attribute translation, metrics translation, dropping routing attribute) are done before branching the code into different sending formats.
> fix(sumologicexporter): translate Telegraf metrics with OTLP format

- CHANGELOG.md
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/sender.go
Currently, when en empty metrics or traces dataset is passed to the Sumo Logic exporter, an empty-bodied request is sent to the backend.
This behavior is in fact in line with what the upstream OTLP HTTP exporter does for all signals - logs, metrics and traces.
This change modifies this behavior for metrics and traces so that the empty request is not sent. This is to prevent an unnecessary network call.
For logs, the current behavior is to not send the empty request when an empty dataset is passed to the exporter, and there is no change to this behavior.
> feat(sumologicexporter): do not send empty OTLP requests

- CHANGELOG.md
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
If the server responds with '400 Bad Request', the exporter should not retry the request.
This is in line what the upstream OTLP HTTP exporter does:
https://github.com/open-telemetry/opentelemetry-collector/blob/v0.55.0/exporter/otlphttpexporter/otlp.go#L181-L184
> feat(sumologicexporter): do not retry on '400 Bad Request' response

- CHANGELOG.md
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
- pkg/processor/k8sprocessor/kube/fake_owner.go
The Node filter should only be used for the Pod informer, as only Pods have the `spec.Node` field. This fixes #651 @mat-rumian
> fix(k8sprocessor): only apply the node filter to Pods

- CHANGELOG.md
- docs/Upgrading.md
- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/exporter.go
- pkg/processor/sumologicschemaprocessor/README.md
- pkg/processor/sumologicschemaprocessor/config.go
- pkg/processor/sumologicschemaprocessor/config_test.go
- pkg/processor/sumologicschemaprocessor/processor.go
- pkg/processor/sumologicschemaprocessor/processor_test.go
- pkg/processor/sumologicschemaprocessor/testdata/config.yaml
- pkg/processor/sumologicschemaprocessor/translate_attributes_processor.go
- pkg/processor/sumologicschemaprocessor/translate_attributes_processor_test.go
Fixes #649 
The `sumologic` exporter modifies data it gets by translating attributes from OpenTelemetry convention to Sumo convention. This PR moves this logic to the `sumologic schema` processor.
Technically this is ready for review, but it might have not been tested properly yet, so I'm marking this as a draft.
> feat(sumologicexporter, sumologicschemaprocessor)!: move translating metadata from sumologic exporter to sumologic schema processor

- docs/Upgrading.md
During the release process, the upgrading instructions were not moved away from the `Unreleased` section.
I believe that this should be added to the release progress, just like the changelog in #679
> docs(upgrading): move instructions from the unreleased section

- CHANGELOG.md
- docs/Upgrading.md
- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/exporter.go
Ref: #255 (this PR does not resolve this yet, since it needs to be removed)
The feature of setting the source headers (and source templates) is now deprecated and is going to be removed in v0.60.0.
> feat(sumologicexporter): deprecate setting source headers

- docs/release.md
The release guide only mentioned how to upgrade the Changelog. However, the Upgrading.md file is also quite important and should be updated in the same way.
Ref: https://github.com/SumoLogic/sumologic-otel-collector/pull/679
> docs: update release guide with adding Upgrading.md updating instructions

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- otelcolbuilder/Makefile
Changes: 
* BoringCrypto is not FIPS-certified on MacOS, removed the build
* BoringCrypto is not FiPS-certified on ARM, removed the build
* CGO must be enabled, enabled it
* Added a step to show symbols to verify
> fix: CI for FIPS builds

- .github/workflows/pull_requests.yml
configuration in github workflow: https://github.com/SumoLogic/sumologic-otel-collector/blob/1fdc63b4bcdfd78a0cc5f927439e910ec3a92d57/.github/workflows/pull_requests.yml#L365 
related failure of github action: https://github.com/SumoLogic/sumologic-otel-collector/runs/7674560442?check_suite_focus=true
> fix(ci): add condition to check symbols only when build related files changed

- CHANGELOG.md
- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/factory.go
- pkg/extension/sumologicextension/README.md
- pkg/processor/cascadingfilterprocessor/README.md
- pkg/processor/cascadingfilterprocessor/factory.go
- pkg/processor/k8sprocessor/README.md
- pkg/processor/k8sprocessor/factory.go
- pkg/processor/metricfrequencyprocessor/README.md
- pkg/processor/metricfrequencyprocessor/factory.go
- pkg/processor/sourceprocessor/README.md
- pkg/processor/sourceprocessor/factory.go
- pkg/processor/sumologicschemaprocessor/README.md
- pkg/processor/sumologicschemaprocessor/factory.go
- pkg/processor/sumologicsyslogprocessor/README.md
- pkg/processor/sumologicsyslogprocessor/factory.go
- pkg/receiver/rawk8seventsreceiver/README.md
- pkg/receiver/rawk8seventsreceiver/factory.go
- pkg/receiver/telegrafreceiver/README.md
- pkg/receiver/telegrafreceiver/factory.go
As for upstream version v0.57.2, the components must have a stability level defined. This PR does this.
I couldn't recall what exactly have we agreed on, so I have set all the levels to **beta**. Feel free to disagree with this.
> feat: define stability levels for components

- docs/Configuration.md
Setting the source headers in sumologic exporter has been deprecated. This commit adds this information to the configuration guide.
Ref: #696
> docs(Configuration): update information about setting source headers

- .github/workflows/release_builds.yml
There was a remaining dependency on a nonexisting job after FIPS builds for darwin were removed.
> ci: fix release workflow

- CHANGELOG.md
- README.md
- docs/release.md
- otelcolbuilder/.otelcol-builder.yaml
Resolves #663
Custom changes in the filter processor have been deprecated in v0.55.0-sumo-0. 
According to the discussion under https://github.com/SumoLogic/sumologic-otel-collector/pull/655, the goal was to stop using any custom changes of the `filter` processor. However, I was not sure what is the status of the contrib. It seems that the `attributes` processor also uses some related changes. I decided not to drop them.
Should we also revert the changes in our contrib fork or not?
> feat(filterprocessor): drop custom changes

- docs/Troubleshooting.md
The upstream docs on troubleshooting contain some basic and very useful instructions, like checking the collector's metrics or adding the `logging` exporter. Every troubleshooting should start with those instructions.
> docs(troubleshooting): link to upstream docs

- .golangci.yaml
- Makefile
- pkg/exporter/sumologicexporter/compress.go
- pkg/exporter/sumologicexporter/compress_test.go
- pkg/exporter/sumologicexporter/fields.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/source_format.go
- pkg/extension/sumologicextension/extension.go
- pkg/processor/cascadingfilterprocessor/bigendianconverter/big_endian_converter.go
- pkg/processor/cascadingfilterprocessor/bigendianconverter/big_endian_converter_test.go
- pkg/processor/k8sprocessor/doc.go
Upgrading to the most recent golangci-lint and re-enabling some linters we disabled while upgrading to Go 1.18. I'm also going to enable `staticcheck` again in a separate PR, as it requires more complex changes.
> chore: upgrade golangci-lint to v1.49

- .golangci.yaml
- pkg/exporter/sumologicexporter/compress_test.go
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
- pkg/extension/sumologicextension/credentials/credentialsstore_localfs.go
- pkg/extension/sumologicextension/extension.go
Re-enable the staticcheck linter which was disabled during the upgrade to go 1.18. With the upgrade to golangci-lint in #715 , it can now be re-enabled. One of the main benefits of this is automated deprecation checking - particularly useful for OT core upgrades.
One of the changes in this PR isn't just syntactic, and has to do with storing pointers to compressors instead of compressors themselves in a bufferpool. I didn't see any performance impact of this, nor any test failures.
> test: re-enable staticcheck linter

- CHANGELOG.md
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
Backporting https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14097
>  test(k8sprocessor): do not skip if other associations are already up to date

- examples/default.yaml
It adds default configuration to examples, which:
* scrapes host metrics
* scrapes logs from the following destinations:
* /var/log/auth.log
* /var/log/syslog
* /var/log/daemon.log
* /var/log/kern.log
* /var/log/dpkg.log
* uses file storage to buffer data
> chore(examples): add default configuration

- CHANGELOG.md
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
- pkg/processor/k8sprocessor/kube/fake_owner.go
- pkg/processor/k8sprocessor/kube/kube.go
- pkg/processor/k8sprocessor/kube/owner.go
- pkg/processor/k8sprocessor/kube/owner_test.go
Information about pod's services can arrive late, i.e. after the pod has been marked as ready. If that happens, the data won't be marked with this information until another update of that pod.
This PR changes this behavior - information about services is no longer cached and is recalculated every time when `GetPod` is called.
This is a less intrusive solution for this problem - an alternative is to remove the whole `map[string]*Pod` from `WatchClient` and recalculate all the attributes every time.
cc: @swiatekm-sumo
> fix(k8sprocessor): keep pod's services information up to date

- otelcolbuilder/Makefile
This adds `make install-builder` arm64 mac support.
> Detect host CPU architecture when installing builder

- CHANGELOG.md
- otelcolbuilder/.gitignore
- otelcolbuilder/cmd/fips.go
This adds an additional file to the main package which:
1. Imports a module that is supposed to guarantee that we're always running in FIPS mode: https://go.googlesource.com/go/+/dev.boringcrypto/src/crypto/tls/fipsonly/fipsonly.go
2. Adds an init check for whether we're using BoringSSL and prints a log line if so
It's not clear whether this is a good enough solution to attest that we're running in FIPS mode. Maybe we should also add a test that tries to use a FIPS-incompatible cipher for TLS and fails?
> feat(build): validate FIPS mode at build time and runtime

- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/config_test.go
A follow-up to the discussion: https://github.com/SumoLogic/sumologic-otel-collector/pull/686#discussion_r978684183
The warnings about removed config options should not be called `deprecation_warning`
> chore(sumologicexporter): rename config errors

- examples/sumologic.yaml
This commit fixes the following error:
2022-10-21T12:42:08.510+0200	error	sumologicextension@v0.57.2-sumo-1/extension.go:297	Unable to store collector credentials, they will be used now but won't be re-used on next run	{"kind": "extension", "name": "sumologic", "collector_name": "mstozek-mac-7e9e719a-5903-487c-8d35-eaa51811cad9", "collector_id": "0000000000355218", "error": "mkdir ~/.otelcol-credentials: no such file or directory"}
Apparently otelcol cannot resolve ~ to home directory properly.
> fix: cannot create credentials directory

- docs/Installation.md
Fixes #790
We probably don't need to show the output of the `docker run` command at all; we don't show it in other examples for running the binary either.
I have also changed the target path of the config file for simplicity and split the command into multiline lines so that it is visible in the viewport without scrolling.
> docs: simplify Docker run instructions

- docs/Installation.md
- scripts/install.sh
Don't use sudo in the script and have it exit if it's not run as root. This way the user has much better control over what it does, and won't be surprised by the script trying to run commands as root quietly.
I haven't added a test for this because it's a major pain to manage Linux users in Go, and the change is simple enough. Existing tests pass because they run as root to begin with.
> fix(scripts/install.sh): don't use sudo

- pkg/scripts_test/command.go
- pkg/scripts_test/install_test.go
- scripts/install.sh
Instead of prompting for confirmation, we should install everything by default and provide flags to disable specific features.
I'm planning to add flags to disable default config creation and systemd configuration in separate PRs.
> feat(scripts/install.sh): do not prompt user for confirmation

- docs/Installation.md
The install script needs to explicitly be run with sudo, and this makes process substitution annoying, as sudo closes any descriptors other than the standard ones. Use a pipe from curl instead.
This was broken in #795. As it, it would result in the following error:
```bash
bash: /dev/fd/63: No such file or directory
```
> docs: update install command

- pkg/scripts_test/command.go
- pkg/scripts_test/install_test.go
- scripts/install.sh
Add a private flag to keep downloaded OT binaries between install script runs. This uses the `-z` curl flag which only downloads the binary if it was changed more recently than the existing file on disk. This is enabled in all tests with the exception of one, which was newly added, and results in significant test speed up (~5 minutes to ~2 minutes).
Looking at the curl changes, we should factor out the common parameters, but I'd like to do that in a separate PR.
> feat(scripts/install.sh): add flag to keep downloads

- pkg/scripts_test/check.go
- pkg/scripts_test/consts.go
- pkg/scripts_test/install_test.go
> test(scripts/install.sh): check config path permissions and ownership

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- CHANGELOG.md
- CONTRIBUTING.md
- Makefile
- otelcolbuilder/Makefile
- otelcolbuilder/cmd/collector_config_test.go
- otelcolbuilder/cmd/testdata/filelog_sumologicexporter_with_persistent_queue_enabled.yaml
- pkg/Makefile.Common
- pkg/configprovider/globprovider/provider_test.go
- pkg/extension/sumologicextension/extension_test.go
- pkg/receiver/rawk8seventsreceiver/receiver_test.go
- pkg/scripts_test/Makefile
- pkg/scripts_test/check.go
- pkg/scripts_test/command.go
- pkg/scripts_test/config.go
- pkg/scripts_test/install_test_unix.go
- pkg/scripts_test/install_test_windows.go
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>
Adds Windows builds to the `Dev builds` & `PRs checks` GitHub Actions CI workflows.
> feat(ci): add windows builds to dev & pr workflows

- scripts/install.sh
The config branch for versions <= 0.57.2 has incorrect credentials directory set. We could fix this by adding a new branch to hold this config, but it's easier to do it with sed inside the install script. Eventually we can delete this once a new version is released.
> fix(scripts/install.sh): credentials folder for versions <= 0.57.2

- docs/release.md
Info about components used, but not present in the list has been added. This should help in upgrading the core.
> docs(release.md): add missing info about supported components

- .circleci/config.yml
Fix for:
```
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```
https://app.circleci.com/pipelines/github/SumoLogic/sumologic-otel-collector/1643/workflows/3b328231-d4c1-4d3b-b78b-332a041d705d/jobs/23
> Update orbs tools versions

- otelcolbuilder/.gitignore
- otelcolbuilder/cmd/collector_config_test.go
- otelcolbuilder/cmd/configprovider.go
- otelcolbuilder/cmd/flags.go
The core upgrade in #826 changed the way command line flags are parsed. Instead of trying to hack around this as before, I simply copied the `flags.go` file from upstream. We should figure out a way to make this less hacky. Making the names public would help, but there should be a simpler way of customizing config providers.
> fix(config): flag parsing after core upgrade

- pkg/scripts_test/install_unix_test.go
- scripts/install.sh
On some systems, most notably RHEL, the PATH for `sudo` is restricted via the `secure_path` option in `sudoers`, and doesn't contain `/usr/local/bin`, where we install otel. This causes the installation verification check to fail, even if the installation may otherwise be valid.
Instead check if the binary is in the PATH, emit a warning if so, and then verify using the full path of the binary.
> fix(scripts/install.sh): verify install correctly if binary not in PATH

- CHANGELOG.md
- otelcolbuilder/.otelcol-builder.yaml
Some components were not bumped in #846, because they had version `v0.64.1` and the upgrading script omitted them.
> fix(otelcolbuilder): bump dependencies to v0.66.0

- CHANGELOG.md
- otelcolbuilder/.otelcol-builder.yaml
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>
The import paths for most upstream Go modules are not a part of the `go.opentelemetry.io/collector` module. Version pinning was not working due to the mismatch.
The issue can be reproduced by running `make build` from the `otelcolbuilder` directory and then checking `./cmd/go.mod` for `v0.67.0` which should not be pulled in.
> fix(otelcolbuilder): use correct upstream modules

- CONTRIBUTING.md
The proposed `go.work` file did not contain all necessary directories, which caused `make golint` to fail.
> docs(contributing.md): update proposed go.work file

- CHANGELOG.md
- pkg/processor/sumologicschemaprocessor/README.md
- pkg/processor/sumologicschemaprocessor/config.go
- pkg/processor/sumologicschemaprocessor/config_test.go
- pkg/processor/sumologicschemaprocessor/nesting_processor.go
- pkg/processor/sumologicschemaprocessor/nesting_processor_test.go
- pkg/processor/sumologicschemaprocessor/testdata/config.yaml
Updates #865 
Nesting subprocessor has gained two config options. It now supports an allowlist and a denylist of prefixes for which the attributes should or should not be translated.
> feat(sumologicschemaprocessor): add allowlist and denylist to nesting processor

- docs/upgrading.md
I have removed the use of Transform processor for source attributes because:
- the provided configuration was invalid
- the configuration of Transform processor has changed greatly between v0.57.2 and v0.66.0 and it's not clear which should be used here
- the Source processor should be the default replacement anyway - it is a direct replacement of that feature. It also supports templating with "%{}" just like the Sumo Logic exporter did.
I have also hopefully made to wording clearer to make it obvious which configuration properties are being removed.
> docs(upgrading): use Source processor instead of Transform processor for source attributes

- CHANGELOG.md
- pkg/processor/sumologicschemaprocessor/README.md
- pkg/processor/sumologicschemaprocessor/aggregate_attributes_processor.go
- pkg/processor/sumologicschemaprocessor/aggregate_attributes_processor_test.go
- pkg/processor/sumologicschemaprocessor/config.go
- pkg/processor/sumologicschemaprocessor/config_test.go
- pkg/processor/sumologicschemaprocessor/processor.go
- pkg/processor/sumologicschemaprocessor/processor_test.go
- pkg/processor/sumologicschemaprocessor/testdata/config.yaml
Updates #866
Done. This is a basic version, which supports only prefixes.
> [processor/sumologicschema]: allow aggregating attributes with given name patterns

- CHANGELOG.md
- pkg/processor/sumologicschemaprocessor/README.md
- pkg/processor/sumologicschemaprocessor/config.go
- pkg/processor/sumologicschemaprocessor/config_test.go
- pkg/processor/sumologicschemaprocessor/nesting_processor.go
- pkg/processor/sumologicschemaprocessor/nesting_processor_test.go
- pkg/processor/sumologicschemaprocessor/testdata/config.yaml
Updates #865 
This PR adds a feature to nesting processor that squashes maps that have only one key-value pair. For example:
```
{
"k8s": {
"pods": {
"a" : "A",
"b": "B"
}
}
}
```
gets squashed into
```
{
"k8s.pods": {
"a" : "A",
"b": "B"
}
}
```
This feature is **disabled** by default. 
Two things to note:
- Perhaps this implementation contains too much map copying, but I wanted to finish this before Christmas and eventually fix later. 
- I tried to create an algorithm that does this while doing the initial nesting, but I found it to be too complex and not necessarily faster.
> feat(sumologicschemaprocessor): add squashing single values in nesting processor

- scripts/install.sh
Update the installation script to not hang on `systemctl status` (https://jira.kumoroku.com/jira/browse/SUMO-206497).
This pull-request makes use of `--no-pager          Do not pipe output into a pager`.
> Install script, do not hang on systemctl status

- pkg/extension/sumologicextension/extension.go
The metadata API now returns an HTTP 204 response.
> Fix metadata api update call, 204 is expected

- scripts/install.sh
Ensure the `unzip` command/tool is available before proceeding with OT collector install.
> Added unzip to installer script check dependencies

- scripts/install.sh
This pull-request makes it so the installation scripts attempts to install the `bc` and `unzip` tools on RHEL systems if they are missing. I have confirmed that it works on RHEL/Rocky 9.
> Install specific missing dependencies on specific platforms

- otelcolbuilder/Makefile
This tag was removed in 0.58.0 and is no longer necessary to enable the persistent queue, which is now included by default.
> fix(build): remove enable_unstable tag

- scripts/install.sh
We should let people on slow Internet connections install otel too. At 180 seconds, you need around 0.6 MBps, which I think is reasonable. This also helps with GitHub hiccups.
> fix(scripts/install.sh): increase download timeout

- pkg/scripts_test/check.go
- pkg/scripts_test/command.go
- pkg/scripts_test/common.go
- pkg/scripts_test/install_unix_test.go
The hostmetrics configuration will only be available from v0.70.0. Right now, the test fails, and this fixes it.
> test(scripts/install.sh): fix hostmetrics test

- pkg/exporter/sumologicexporter/README.md
Added a note that `max_body_request_size` config option does not apply for otlp data.
> docs(sumologicexporter): add info about batching for otlp source

- pkg/scripts_test/check.go
- pkg/scripts_test/consts.go
- scripts/install.sh
Directories need a +x permission. Fixes a regression introduced by #906
> fix(install/script): config dir permissions

- docs/best-practices.md
Added recommendations about the batching processor, especially about setting the upper bound for batch sizes.
The default values have been taken from the helm chart: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/de55cdd16404d10769063353c3ca4f8c2f4026e5/deploy/helm/sumologic/conf/logs/otelcol/config.yaml#L87-L92
The recommended value `5*send_batch_size` was approximated basing on production data. In the case I was investigating, in normal situation there weren't many spikes greater than that value, but when it got out of control, it could get up to `30*send_batch_size` and then it did cause problems.
> docs(best-practices.md): add recommended config for batching processor

- examples/sumologic-windows.yaml
- examples/sumologic.yaml
- packaging/msi/SumoLogic.wixext/SumoLogicTests/TestData/with-extensions-block.yaml
- packaging/msi/SumoLogic.wixext/SumoLogicTests/TestData/without-extensions-block.yaml
We shouldn't be accepting connections from outside by default. The assumption is that these configurations are supposed to serve local applications. If the user wants to receive data from the network, they should explicitly make that choice.
> fix(examples): don't bind to 0.0.0.0 by default

- pkg/receiver/rawk8seventsreceiver/receiver_test.go
This test was flaky because it was erroneously using an assertion inside an `assert.Eventually` call. If the inner assertion failed even once, the whole test would fail.
> test(rawk8seventsreceiver): fix flaky test

- pkg/scripts_test/consts.go
- scripts/install.sh
Set permissions for config directory in `/etc/` before putting config files there. `/etc/` is world-readable by default, and credentials can be leaked this way.
> fix(scripts/install.sh): config dir permissions

- scripts/install.sh
`unzip` isn't installed by default in Ubuntu, and not required in the script's happy path, so I've made the check conditional.
> fix(scripts/install.sh): only require unzip when necessary

- scripts/install.sh
`bc` is missing on the default Debian 9 install, and we only use it to do version comparisons. Instead I used bash parameter expansion to parse the version, and compare the numbers as integers, which bash can do natively.
This is based on #924
> fix(scripts/install.sh) don't use bc

- pkg/scripts_test/command.go
- pkg/scripts_test/install_unix_test.go
- scripts/install.sh
We currently recommend to use the script by piping the content to bash. This makes it difficult to prompt the user for input in a platform-agnostic way. Require --yes for uninstallation until we figure it out.
This replaces #810
> feat(scripts/install.sh): require --yes for uninstallation

- scripts/install.sh
Trying to install echo using yum on RHEL was a mistake.
> fix(scripts/install.sh): don't try to install echo

- docs/installation.md
- examples/ansible/install_sumologic_otel_collector.yaml
- examples/chef/sumologic-otel-collector/resources/default.rb
- examples/puppet/modules/install_otel_collector/manifests/init.pp
- pkg/scripts_test/check.go
- pkg/scripts_test/command.go
- pkg/scripts_test/consts.go
- pkg/scripts_test/install_unix_test.go
- scripts/install.sh
I'm leaving the actual option in, as it's currently still displayed in the UI, but I'm removing it from documentation and manifests for Chef, Puppet and Ansible.
> feat(scripts/install.sh): don't pass install token via command line

- examples/sumologic.yaml
With this change, we aren't binding to 0.0.0.0 by default anywhere.
> fix(examples): don't bind health check endpoint to 0.0.0.0

- pkg/scripts_test/install_linux_amd64_test.go
The version isn't set correctly for v0.70.0-sumo-1 due to commit 7b02da7. The binary itself is fine.
This should be reverted after v0.71.0 is released.
> test(scripts/install.sh): disable FIPS version test

- otelcolbuilder/.otelcol-builder.yaml
- otelcolbuilder/Makefile
This reverts commit 7b02da720c7746915815516d367a109525d58acb.
This doesn't actually work, and the version ends up as literally `$(VERSION)$(FIPS_SUFFIX)`. Need to find a different way to set these variables.
> Revert "chore(otelcolbuilder): move deprecated CLI options to otelcol-builder.yaml"

- CHANGELOG.md
- pkg/processor/k8sprocessor/client_test.go
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
- pkg/processor/k8sprocessor/kube/kube.go
- pkg/processor/k8sprocessor/processor.go
We had a race condition where we'd update Pod metadata in `GetPod` while only holding a read lock. In circumstances where two batches of data would arrive from the same Pod in quick succession, we'd get a panic due to concurrent map writes.
I fixed this by changing the interface to only return an attributes map and explicitly making that a copy of what's in the Pod attributes.
> fix(k8sprocessor): race condition when getting Pod data

- CHANGELOG.md
- otelcolbuilder/.otelcol-builder.yaml
- otelcolbuilder/Makefile
Backport of #942 to v0.70.0
The script tests failing here is expected.
> [Backport v0.70.0] Revert "chore(otelcolbuilder): move deprecated CLI options to otelcol-builder.yaml"

- CHANGELOG.md
- pkg/processor/sourceprocessor/factory.go
- pkg/processor/sourceprocessor/source_category_filler.go
- pkg/processor/sourceprocessor/source_category_filler_test.go
- pkg/processor/sourceprocessor/source_processor.go
- pkg/processor/sourceprocessor/source_processor_test.go
They proved useful when debugging why the source category filler wasn't working.
> feat(sourceprocessor): add debug logs for source category filler

- pkg/scripts_test/install_linux_amd64_test.go
This reverts commit ca7eaed0c86a73350b1df59222eee47a83f4903b. With https://github.com/SumoLogic/sumologic-otel-collector/releases/tag/v0.70.0-sumo-2 out, this test can be enabled again.
Fixes #940
> Revert "test(scripts/install.sh): disable FIPS version test"

- pkg/scripts_test/check.go
- pkg/scripts_test/install_unix_test.go
- scripts/install.sh
Adds`Uninstallation completed` after uninstallation process
> feat(scripts/install.sh): add information after uninstallation

- CHANGELOG.md
- pkg/processor/sourceprocessor/README.md
- pkg/processor/sourceprocessor/config.go
- pkg/processor/sourceprocessor/config_test.go
- pkg/processor/sourceprocessor/factory.go
- pkg/processor/sourceprocessor/source_category_filler.go
- pkg/processor/sourceprocessor/source_processor_test.go
It was hardcoded to `k8s.container.name`.
This change makes it configurable.
> feat(sourceprocessor): make container name attribute configurable

- pkg/exporter/syslogexporter/examples/config.yaml
`drop_invalid_messages` parameter is not supported by syslogexporter
> fix(syslogexporter) remove drop_invalid_messages parameter from example config

- .github/workflows/release_builds.yml
Double quotes are not allowed in GHA conditional expressions.
> ci: fix Windows signing step

- pkg/Makefile.Common
- pkg/processor/cascadingfilterprocessor/idbatcher/id_batcher_test.go
- pkg/processor/cascadingfilterprocessor/processor_test.go
- pkg/receiver/rawk8seventsreceiver/receiver_test.go
I fixed a small problem in the event receiver test.
I reduced some numbers in cascading filter processor tests, as the race detector has a limit of 8192 goroutines on Windows.
> test: enable race detection in Go tests

- scripts/install.sh
Do not expose token in sed command as it can be saw on processes list
> refactor(scripts/install): do not expose token in sed command

- docs/BestPractices.md
- docs/Comparison.md
- docs/Configuration.md
- docs/Installation.md
- docs/KnownIssues.md
- docs/Migration.md
- docs/OpenTelemetryConcepts.md
- docs/Performance.md
- docs/Troubleshooting.md
- docs/Upgrading.md
- docs/UpstreamRelation.md
We've renamed docs to kebab-case in #823, and the old docs files were left containing only links to the new ones. This change removes the old files completely.
> docs: remove uppercase docs files

- scripts/install.sh
This ignores curl errors as we fallback to different methods of getting latest version
> feat(scripts/install):do not fail if unable to get available versions

- scripts/install.sh
Do not expose installation token on stdout
> fix: do not expose installation token

- pkg/scripts_test/check.go
- pkg/scripts_test/install_unix_test.go
- scripts/install.sh
If we install once without `--hostmetrics` and then with `hostmetrics` switch, the `hostmetrics.yaml` configuration will have invalid owner
> fix: ensure correct permissions for hostmetrics after upgrade

- scripts/install.sh
```
Installing linux hostmetrics configuration
We are going to set up a systemd service
Creating user and group
Creating ACL grants on log paths
setfacl command not found, skipping ACL creation for system log file paths.
You can fix it manually by installing setfacl and executing the following commands:
-> setfacl -R -m d:u:otelcol-sumo:r-x,u:otelcol-sumo:r-x,g:otelcol-sumo:r-x /var/log/
Changing ownership for config and storage
Getting service configuration
######################################################################## 100.0%
Enable otelcol-sumo service
Created symlink /etc/systemd/system/multi-user.target.wants/otelcol-sumo.service → /etc/systemd/system/otelcol-sumo.service.
Starting otelcol-sumo service
Waiting 10s before checking statu
```
> feat(scripts/install.sh): be more descriptive about missing setfacl

- docs/installation.md
Removes the incorrect "(x86-64)" name from MacOS arm64 section title.
Renames "Apple M1" to "Apple silicon" as in official [Apple docs](https://support.apple.com/en-us/HT211814).
> docs(installation): fix MacOS arm64 architecture name

- .github/workflows/dev_builds.yml
The `display-workflow-run-url-interval` is the interval between API calls to attempt to determine a remotely triggered Workflow Run ID. As the packaging workflow requires the Dev Build workflow to be complete I changed the interval to 1 second from the default of 1 minute. This is a short enough time but if we start to run into issues then we'll need to add a job step to the packaging workflow that waits for the completion of the corresponding Dev Build workflow.
> fix: decrease display-workflow-run-url-interval

- CHANGELOG.md
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
If the format is otlp, sumologic expoter should behave the same way as otlphttp exporter when it comes to
adding the per-signal url suffixes.
> feat(sumologicexporter): use otlp url suffixes

- pkg/scripts_test/check.go
- pkg/scripts_test/consts.go
- pkg/scripts_test/go.mod
- pkg/scripts_test/go.sum
- pkg/scripts_test/install_unix_test.go
- scripts/install.sh
Install script should behave the same like we document manual steps for systemd installation
> feat: keep token in env variable instead of config file

- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/config_test.go
We were trying to be helpful by helping the user migrate off unsupported properties, but links that point to nowhere do not help much.
This changes the links to point straight to the upgrade docs instead of release notes.
I also point to the `main` branch of the upgrade docs, because there have been, and there might be more, changes/improvements to these docs.
> fix(sumologicexporter): fix links to upgrade docs

- docs/comparison.md
- docs/configuration.md
- docs/installation.md
- docs/migration.md
- docs/upgrading.md
- examples/config_cpu_load_metrics.yaml
- examples/sumologic-windows.yaml
- examples/sumologic.yaml
- examples/verify_installation.yaml
- packaging/msi/SumoLogic.wixext/SumoLogic.wixext/ConfigUpdater.cs
- packaging/msi/SumoLogic.wixext/SumoLogic.wixext/CustomAction.cs
- packaging/msi/SumoLogic.wixext/SumoLogicTests/ConfigUpdaterTests.cs
- packaging/msi/SumoLogic.wixext/SumoLogicTests/TestData/with-extensions-block.yaml
- packaging/msi/wix/assets/common.yaml
- packaging/msi/wix/package.wxs
- pkg/scripts_test/config.go
- scripts/install.sh
This is continuation of #969
ToDo:
- support for windows both install_token and installation_token
- update scripts_tests
> feat: rename install_token to installation token

- otelcolbuilder/cmd/configprovider.go
This feature is nowhere to be found in the documentation, so I omitted adding any additional documentation steps to not cause confusion.
> feat: enable `extension.sumologic.updateCollectorMetadata` feature gate by default

- scripts/install.ps1
Implements an install script in PowerShell for Windows that can detect OS type, CPU architecture, installed otelcol-sumo version, latest otelcol-sumo version, and can accept the following params:
* `-Version <version>`
* `-InstallationToken <installation_token>` (defaults to the `SUMOLOGIC_INSTALLATION_TOKEN` envvar)
* `-Tags <tags_as_hashtable>` (e.g. `-Tags @{ tag1 = "foo"; tag2 = "bar" }`)
The following command can be used to download & install after replacing `replaceme` with your installation token:
```powershell
Set-ExecutionPolicy RemoteSigned -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; $uri = "https://raw.githubusercontent.com/SumoLogic/sumologic-otel-collector/feat/install-ps1/scripts/ins …
```
> feat: add scripts/install.ps1

- pkg/scripts_test/check.go
- pkg/scripts_test/command.go
- pkg/scripts_test/common.go
- pkg/scripts_test/consts.go
- pkg/scripts_test/install_unix_test.go
- scripts/install.sh
```
Supported arguments:
-i, --installation-token <token>      Installation token. It has precedence over 'SUMOLOGIC_INSTALLATION_TOKEN' env variable.
-k, --skip-installation-token              Skips requirement for installation token.
This option do not disable default configuration creation.
-t, --tag <key=value>                 Sets tag for collector. This argument can be use multiple times. One per tag.
-w, --download-only                   Download new binary only and skip configuration part.
-u, --uninstall                       Removes Sumo Logic Distribution for OpenTelemetry Collector from the system and
disable Systemd service eventually.
Use with '--purge' to remove all configurations as well.
-p, --purge                           It has to be used with '--uninstall'.
It …
```
> feat(scripts/install.sh): expose timeout configuration

- docs/comparison.md
- examples/config_logging.yaml
- examples/logs_json/config.yaml
- pkg/extension/sumologicextension/testdata/config.yaml
`logLevel` only worked due to a bug in the upstream that was "fixed" in v0.71.0, breaking many configurations.
> docs: change `logLevel` to `loglevel` for Logging exporter

- scripts/install.ps1
This pull-request add the `-InstallHostMetrics $True` installation flag to install host metrics collection.
For example:
```
Set-ExecutionPolicy RemoteSigned -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; $uri = "https://raw.githubusercontent.com/SumoLogic/sumologic-otel-collector/main/scripts/install.ps1"; $path="${env:TEMP}\install.ps1"; (New-Object System.Net.WebClient).DownloadFile($uri, $path); . $path -InstallationToken replace-me -Tags @{tag1 = "foo"; tag2 = "bar"} -InstallHostMetrics $True
```
Related to: https://github.com/SumoLogic/sumologic-otel-collector/pull/1034
> Added install host metrics to windows powershell install script

- CHANGELOG.md
- scripts/install.ps1
If the Sumo Logic OpenTelemtry Collector is installed and the `otelcol-sumo.exe` binary does not exist then the `install.ps1` script will currently throw an error and not execute. This change will show a warning and continue as if no installation was detected.
> fix(scripts/install.ps1): treat app as not installed if otelcol-sumo.exe is missing

- CHANGELOG.md
- docs/upgrading.md
- pkg/exporter/sumologicexporter/go.mod
- pkg/exporter/sumologicexporter/go.sum
- pkg/extension/opampextension/go.mod
- pkg/extension/opampextension/go.sum
- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_test.go
- pkg/extension/sumologicextension/go.mod
- pkg/extension/sumologicextension/go.sum
Use FQDN before hostname for the default collector name and metadata. The value is taken from the `go-fqdn` package, which is also what resource detection processor does.
> fix(sumologicextension)!: use fqdn before os.Hostname

- CHANGELOG.md
- pkg/exporter/syslogexporter/config.go
- pkg/exporter/syslogexporter/exporter.go
- pkg/exporter/syslogexporter/exporter_test.go
- pkg/exporter/syslogexporter/factory.go
- pkg/exporter/syslogexporter/factory_test.go
- pkg/exporter/syslogexporter/go.mod
- pkg/exporter/syslogexporter/syslog.go
- pkg/exporter/syslogexporter/utils.go
- pkg/exporter/syslogexporter/utils_test.go
Summary of changes:
-   fix(syslogexporter): set default settings for sending_queue and retry_on_failure
default setting are now set to defaults in exporterhelper,
one expection - sending queue is enabled by default in syslog exporter
-   chore(syslogexporter): fix errors reported by golangci-lint in opentelemetry-collector-contrib repository
List of reported errors:
```
/Users/kkujawa/git/opentelemetry-collector-contrib/.tools/golangci-lint run --allow-parallel-runners --build-tags integration
utils.go:38:5: increment-decrement: should replace errorsWithCounts[i].count += 1 with errorsWithCounts[i].count++ (revive)
errorsWithCounts[i].count += 1
^
config.go:28:2: error-naming: error var unsupportedPort should have name of the form errFoo (revive)
unsupportedPort     = …
```
> [syslogexporter] set defaults for sending_queue and retry_on_failure and fix errors reported by golangci-lint

- pkg/exporter/syslogexporter/README.md
Stability level is set to alpha in the code: https://github.com/SumoLogic/sumologic-otel-collector/blob/69be5da95556afbbf50c2265d698c7b116e5cc19/pkg/exporter/syslogexporter/factory.go#L29
> docs(syslogexporter) change stability level in README.md

- CHANGELOG.md
- pkg/exporter/sumologicexporter/prometheus_formatter.go
- pkg/exporter/sumologicexporter/prometheus_formatter_test.go
For Prometheus histogram metrics, the timeseries representing buckets should have a `_bucket` suffix.
See https://prometheus.io/docs/concepts/metric_types/#histogram.
> fix(sumologicexporter): Prometheus histogram metric names

- otelcolbuilder/.otelcol-builder.yaml
Stanza is now a public package, so this replace doesn't do anything, and can safely be removed.
> chore(build): remove unnecessary replace

- scripts/install.sh
Releated to https://github.com/SumoLogic/sumologic-otel-collector/issues/1106#issuecomment-1520758676
> install script, include log dir acl default group

- otelcolbuilder/.otelcol-builder.yaml
Some components were accidentally removed in a previous change, adding them back.
> fix: missing components

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
* Stop using `set-output` as per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
* Upgrade external actions in relation to the above as well
* Use setup-go caching instead of our own
* Fix the markdown-link-check configuration to only check changed files and only show errors in output
> ci: deprecation fixes

- CHANGELOG.md
- pkg/processor/k8sprocessor/README.md
- pkg/processor/k8sprocessor/config_test.go
- pkg/processor/k8sprocessor/go.mod
- pkg/processor/k8sprocessor/go.sum
- pkg/processor/k8sprocessor/options.go
- pkg/processor/k8sprocessor/options_test.go
- pkg/processor/k8sprocessor/testdata/config.yaml
Make it possible to specify metadata fields for k8sprocessor using the otel semantic convention. This will make it easier to migrate to the upstream processor in the future. The older format is still supported, though all the examples use the newer one.
> feat(k8sprocessor): support otel semantic convention in config

- otelcolbuilder/Makefile
Setting GODEBUG doesn't do anything at build time. Instead, the same effect can be accomplished by setting the right build tag.
I successfully verified that this works in K8s.
> fix(build): use native Go dns resolver for fips binaries

- Makefile
- otelcolbuilder/cmd/Makefile
- pkg/Makefile.Common
- pkg/receiver/rawk8seventsreceiver/receiver_test.go
The `-count 1` parameter explicitly causes test results to not be cached. Remove it.
Fix an issue with the make test command only running for the first package. Just make and bash things.
This also turned up some remaining flaky tests in rawk8sevents receiver, which were leftover from #919.
> test: cache test results

- CHANGELOG.md
- README.md
- otelcolbuilder/.otelcol-builder.yaml
This adds experimental logs support to the SQL Query receiver.
This feature is currently under review in the OpenTelemetry Collector Contrib repository:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20730
> feat(receiver/sqlquery): add experimental logs support

- CHANGELOG.md
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
By default we are encoding htlm characters like `<`, `>`, `&`. It is unexpected for our customers
log:
```
{"log": "<<<<>>>>>"}
```
output to Sumo Logic
```
2023-05-31T06:01:09.357Z DEBUG [receiver_mock::router] log => {"log":"{\"log\": \"\u003c\u003c\u003c\u003c\u003e\u003e\u003e\u003e\u003e\"}","log.file.path_resolved":"/home/drosiek/projects/sumologic-otel-collector/tmp/logs/unicode.json","timestamp":1685512869155}
```
> fix: do not send html special characters as unicode

- CHANGELOG.md
- pkg/extension/sumologicextension/credentials/credentialsstore_localfs.go
- pkg/extension/sumologicextension/credentials/credentialsstore_localfs_test.go
Fixes #1147. We simply try to ensure the credentials directory exists and has the right permissions when the credentials store is instantiated.
> fix(sumologicextension): check credentials dir at start

- CHANGELOG.md
- pkg/extension/sumologicextension/credentials/credentialsstore_localfs.go
- pkg/extension/sumologicextension/credentials/credentialsstore_localfs_test.go
- pkg/extension/sumologicextension/credentials/store.go
- pkg/extension/sumologicextension/extension.go
It's feasible that someone might want to run the collector without a writable credentials directory. In that case, we should continue running if `force_registration: true` is set, instead of failing at start time.
This PR also correctly identifies #1152 as a breaking change in the changelog.
> fix(sumoextension): skip credentials dir check if registration is forced

- .circleci/config.yml
- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- .golangci.yaml
- Dockerfile_dev
- Dockerfile_local
- Makefile
- vagrant/provision.sh
Upstream releases are built with 1.20, so we should follow suit. I've also cut down on duplication in the CI while at it.
> chore: upgrade Go to 1.20

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- .github/workflows/workflow-build.yml
- .github/workflows/workflow-test.yml
This PR adds reusable workflows for building otel binaries and running tests. It also makes some changes to behaviour relative to the current state.
Caching now works differently. We still have a separate cache per OS and architecture, but the cache is only ever saved on `main`, and branches just use it. This is to cut down on unnecessary branch caches, which is especially important now that we also save the build cache, which significantly speeds up execution.
For this reason, we now always run tests on main - we need to build the test cache for branches.
I've left the release workflow alone for now, as it might need to be refactored further to use the new build workflow, and I didn't want to make this PR more complicated than it already is. It might be easier to review commit-by-commit. …
> ci: refactor PR and dev workflows

- otelcolbuilder/cmd/configprovider.go
This is now disabled by default in upstream as well, as per https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23229. See also #1139, which I'm going to unpin and close in the future.
> chore: don't disable pkg.translator.prometheus.NormalizeName by default

- .github/workflows/workflow-build.yml
- CHANGELOG.md
- otelcolbuilder/cmd/configprovider.go
Due to our config provider override, we were exiting with an error when using built-in commands like `components`. Fix this.
> fix(build): allow otel commands to be used

- CHANGELOG.md
- packaging/msi/SumoLogic.wixext/SumoLogic.wixext/SumoLogic.wixext.csproj
- packaging/msi/wix/folders.wxs
- packaging/msi/wix/otelcol-sumo.wixproj
- packaging/msi/wix/ui/otelcol-sumo.wxs
- packaging/msi/wix/variables.wxi
Bumps the WiX toolset version from 4.0.0-preview.1 to 4.0.1.
In order to get this to build I had to update some of our custom WixUI code:
* The UI element's `Id` attribute now requires the platform that the UI is built for.
* The `Print` control for the EULA had no action and did nothing. I've added the proper line to fix it.
I found a few other recommendations and one other bug:
* The `Next` control for the `CustomizeDlg` page was going to `VerifyReadyDlg` instead of `ConfigurationDlg`. This prevented the dialog that asks for the `InstallToken` and `Tags` from appearing unless the  `Back` control was clicked on the `VerifyReadyDlg` page.
* Removed the `PlatformProgramFilesFolder` variable and logic to determine which Program Files directory to use depending on the platform. This is now …
> chore(packaging): wix 4.0.1

- examples/conf.d/linux.yaml
- examples/conf.d/windows.yaml
Use two more configuration properties
to prevent unneeded error logs from the collector.
> fix: mute more errors when collecting host metrics

- CHANGELOG.md
- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/otlp.go
- pkg/exporter/sumologicexporter/otlp_test.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
Sumo doesn't currently support OTLP Histograms. In the interim, we can at least make sure sending a histogram via OTLP and Prometheus gives the same result. We already have the logic for the Prometheus format, and this PR also implements it for OTLP. This comes down to decomposing the Histogram into individual sum, count and bucket metrics.
The behaviour is configurable and disabled by default.
> feat(sumologicexporter): add option to decompose OTLP Histograms

- otelcolbuilder/Makefile
Changes in #1192 most likely used incorrect username to sign the binaries.
> chore: change Mac signing username to otel-mac-certs

- .github/workflows/release_builds.yml
- .github/workflows/workflow-build.yml
Removes the broken debugging step in the build and release CI workflows showing the included collector components and their go module versions.
This information is baked into the executable. To see components run the components command `otelcol-sumo components`. If more subtle debugging is required and knowing the module versions is helpful, there is a workaround until go1.22 is available with the fix for `go version -m` (https://github.com/golang/go/issues/61644). Inspect the binary in a platform specific way.
e.g. `objcopy -O binary -j .go.buildinfo otelcol-sumo-0.80.0-sumo-0-linux_amd64 buildinfo.txt`
Closes https://github.com/SumoLogic/sumologic-otel-collector/issues/1190
> chore(ci): Remove Included Modules Report from CI

- README.md
- otelcolbuilder/.otelcol-builder.yaml
We switched to using a fork of the SQL Query receiver in v0.78.0 to introduce logs support before it was available in upstream. Now that upstream has logs support, we can remove the override.
This change is actually a bit belated. We could and should've done it in v0.80.0, as the upstream already included logs support in it.
> feat(receiver/sqlquery): go back to using upstream receiver

- Makefile
The long versions of `cut` flags are not supported in MacOS.
> chore: fix `make update-ot` in MacOS

- pkg/receiver/rawk8seventsreceiver/receiver_test.go
A likely mistype in rawk8seventsreceiver.TestNoStorage causes a data race. Corrected the typo to fix the race case.
CI Failure: https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/6099766017/job/16552657270
```==================
WARNING: DATA RACE
Write at 0x00c00029e7e0 by goroutine 55:
github.com/SumoLogic/sumologic-otel-collector/pkg/receiver/rawk8seventsreceiver.TestNoStorage()
/home/runner/work/sumologic-otel-collector/sumologic-otel-collector/pkg/receiver/rawk8seventsreceiver/receiver_test.go:341 +0x472
testing.tRunner()
/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1576 +0x216
testing.(*T).Run.func1()
/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1629 +0x47
Previous read at 0x00c00029e7e0 by goroutine 61:
....
==================
--- FAIL: …
```
> chore: fix racey test case in rawk8seventsreceiver

- CHANGELOG.md
- pkg/scripts_test/check_linux.go
- pkg/scripts_test/common.go
- pkg/scripts_test/install_unix_test.go
- scripts/install.sh
A bug currently exists where selinux records are sometimes not set for the otelcol-sumo binary. This will occur if the systemd unit file exists when installing but the otelcol-sumo binary does not. For example, attempting to install after an uninstallation without purging configs.
I've removed the logic that checks if the systemd unit file already exists. This fixes the bug described and will also ensure that users are always using the correct systemd unit file for the version of the collector they're installing.
> fix(install.sh): ensure selinux records are created

- README.md
I flipped around the links in README.md into their intended positions. This will make the links go to the right place for the resource and remote observer processors.
> Update README.md to fix Issue #1251

- .github/workflows/workflow-build.yml
- CHANGELOG.md
- ci/build-fips-action/Dockerfile
- ci/build-fips-action/action.yml
- ci/build-fips-action/entrypoint.sh
- otelcolbuilder/Makefile
The `linux/amd64` FIPS binary is currently built using GLIBC 2.28. Some supported Linux distributions use an older version of GLIBC and the binary we produce is incompatible as a result. This change updates CI to build the binary using the `amazonlinux:2` container image which has GLIBC 2.26.
> chore(ci): build fips binary w/glibc 2.26

- CHANGELOG.md
- README.md
- otelcolbuilder/.otelcol-builder.yaml
They were added in upstream `v0.86.0`.
> feat: add `debug` exporter and `routing` connector

- .github/workflows/dev_builds.yml
- .github/workflows/workflow-build.yml
- otelcolbuilder/Makefile
- otelcolbuilder/cmd/fips.go
- packaging/msi/wix/otelcol-sumo.wixproj
Adds a new `windows/amd64` FIPS binary and a new corresponding MSI package. Test CI run: https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/6397614173
I validated the new FIPS binary is installed by the new MSI package by both verifying the checksum of the installed `otelcol-sumo.exe` file and using `go tool nm .\otelcol-sumo.exe | Select-String vendor/github.com/microsoft/go-crypto-winnative/internal/bcrypt.GetFipsAlgorithmMode`.
> ci: add fips build & msi for windows/amd64

- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_darwin_test.go
Adds a hack to work around issue https://github.com/SumoLogic/sumologic-otel-collector/issues/1295
> Bypass FQDN resolution in darwin tests

- docs/release.md
Removes old instructions that don't apply after intruduction of Towncrier.
> docs(release): update instructions after introducing Towncrier

- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/go.mod
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
Refs: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25121
> chore: remove `multierr` package in favor of built-in `errors.Join`

- .changelog/1306.fixed.txt
- scripts/install.sh
This dependency is necessary for using semanage, which is needed to do SELinux relabeling.
> fix(install): install policycoreutils on RHEL if missing

- pkg/processor/k8sprocessor/go.mod
- pkg/processor/k8sprocessor/go.sum
- pkg/processor/k8sprocessor/kube/kube.go
- pkg/processor/k8sprocessor/pod_association.go
- pkg/processor/k8sprocessor/processor_test.go
- pkg/processor/sumologicschemaprocessor/cloud_namespace_processor.go
- pkg/processor/sumologicschemaprocessor/go.mod
- pkg/processor/sumologicschemaprocessor/go.sum
Changes usages of package [go.opentelemetry.io/collector/model/semconv/](https://pkg.go.dev/go.opentelemetry.io/collector/model/semconv) to latest [go.opentelemetry.io/collector/semconv/](https://pkg.go.dev/go.opentelemetry.io/collector/semconv) package (currently `v1.18.0` as of collector `v0.88.0`). I have verified that the used conventions haven't changed between versions.
> chore: replace deprecated module go.opentelemetry.io/collector/model

- pkg/receiver/jobreceiver/output/logentries/handler.go
Ran into a logging bug while observing what is likely a more important bug: #1309.
We should not use the `%w` placeholder unless constructing an error. The output is something like "%w{ fs.PathError {...} }", and doesn't give the reader the actual useful error message.
> fix logging in monitoring job receiver

- .changelog/1317.fixed.txt
- .github/workflows/release_builds.yml
Related to: https://github.com/SumoLogic/sumologic-otel-collector/pull/1257
At this moment dev FIPS binary is built with glibc 2.26 but release FIPS binary is built with glibc 2.28 which is not available on Linux Amazon 2
> fix: build release fips binary w/glibc 2.26

- otelcolbuilder/Makefile
The sumologic OT collector metadata service has a limit of 32 characters for version number. When we publish a dev build the additional `-fips` suffix puts us over the 32 character limit. This change shortens the commit sha abbreviation so that we'll stay under 32 characters.
> Use shorter SHA abbreviation for dev build version tags

- docs/configuration.md
Provide brief instructions on running the collector with --remote-config. This section will probably get some updates over time as there are some aspects of OpAmp remote configuration that are not finalized yet, but this will give people a reasonable starting point.
> Add docs for --remote-config flag

- .github/workflows/release_builds.yml
- scripts/install.ps1
Adds a FIPS release build for `windows/amd64` and a new `-Fips` flag for the `install.ps1` script. This shouldn't be merged until we're approved to use Microsoft's fork of Go.
I tested this on a fork of this repository. CI run https://github.com/sensu/sumologic-otel-collector/actions/runs/6822421395 & release https://github.com/sensu/sumologic-otel-collector/releases.
> Add FIPS MSI build & FIPS install.ps1 flag

- README.md
We don't have any components "with minor additions" and hopefully we won't have any anymore.
> docs: remove note on components with `*` asterisk

- .changelog/1340.changed.txt
- .changelog/1344.changed.txt
- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- .github/workflows/workflow-build.yml
- .github/workflows/workflow-test.yml
- Dockerfile_local
- vagrant/provision.sh
I used more flexible version constraints where I could, so we automatically use the latest minor version.
> chore: update Go to 1.21

- .changelog/1346.fixed.txt
- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- .github/workflows/workflow-build.yml
- .github/workflows/workflow-test.yml
- Dockerfile_local
- vagrant/provision.sh
There's a problem with the Windows FIPS build on Go 1.21. I'm reverting that change for now.
I've also added this build to the PR checks, as it was missing there.
> build: revert back to Go 1.20

- .changelog/1341.breaking.txt
- README.md
- docs/migration.md
- docs/upgrading.md
- otelcolbuilder/.otelcol-builder.yaml
Fixes https://github.com/SumoLogic/sumologic-otel-collector/issues/1200
> feat(exporter/syslog)!: replace syslog exporter with syslog exporter from opentelemetry-collector-contrib

- .changelog/1342.changed.txt
- pkg/exporter/syslogexporter/README.md
- pkg/exporter/syslogexporter/factory.go
> feat(exporter/syslog): deprecate syslog exporter in favor of upstream version of syslog exporter

- scripts/install.sh
```
➜  sumologic-otel-collector git:(drosiek-align-installation-script) ./scripts/install.sh --help                                                                                                                                                                               
Detected OS type:       linux
Detected architecture:  amd64
Usage: bash install.sh [--installation-token <token>] [--tag <key>=<value> [ --tag ...]] [--api <url>] [--version <version>] \
[--yes] [--version <version>] [--help]
Supported arguments:
-i, --installation-token <token>      Installation token. It has precedence over 'SUMOLOGIC_INSTALLATION_TOKEN' env variable.
-k, --skip-installation-token         Skips requirement for installation token.
This option do not disable default configuration creation.
-t, --tag …
```
> chore(scripts/install.sh): align param descriptions

- .changelog/1201.breaking.txt
- docs/upgrading.md
- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/factory.go
- pkg/exporter/sumologicexporter/factory_test.go
The upstream issue that necessitated this configuration was closed in 2022, and special treatment is no longer required.
> chore: remove routing_attributes_to_drop

- .changelog/1377.changed.txt
- docs/upgrading.md
- pkg/exporter/sumologicexporter/exporter.go
Deprecate `json_logs` in favor of `transform` processor
> docs(upgrading): deprecate json_logs

- .changelog/1383.changed.txt
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
- pkg/exporter/sumologicexporter/test_data_test.go
- pkg/exporter/syslogexporter/exporter.go
Ensure immutability by marking logs, traces and metrics read only in unit tests
> feat(sumologicexporter): ensure immutability

- .changelog/1385.changed.txt
- pkg/extension/opampextension/config.go
- pkg/extension/opampextension/config_test.go
The `opamp` extension configuration was added to `sumologic.yaml` as part of https://github.com/SumoLogic/sumologic-otel-collector/pull/1343. The extension is not enabled by default. This initial configuration is intended to aid in the reliability and formatting of setting up remote management via the installation script (`install.sh`). Unfortunately, the extension validation currently ensures the `remote_configuration_directory` is readable, causing regular installations to fail, for example:
```
Dec 12 14:06:40 ip-172-31-27-232 otelcol-sumo[1449]: Error: invalid configuration: extensions::opamp: opamp remote_configuration_directory /etc/otelcol-sumo/opamp.d must be readable: stat /etc/otelcol-sumo/opamp.d: no such file or directory
Dec 12 14:06:40 ip-172-31-27-232 otelcol-sumo[1449]: …
```
> Remove opamp remote config dir readable validation

- ci/build-fips-action/Dockerfile
- ci/build-fips-action/action.yml
- ci/build-fips-action/entrypoint.sh
Restore ci/build-fips-action to fix release builds. This is a temporary remedy until we have time to properly (and carefully) incorporate the new fips toolchain static builds from https://github.com/SumoLogic/sumologic-otel-collector/pull/1381
> Restore ci/build-fips-action to fix release builds

- .changelog/1400.fixed.txt
- pkg/processor/k8sprocessor/options.go
- pkg/processor/k8sprocessor/options_test.go
Fixes #1380 
Note: this change causes all possible case variants to be correct (see the newly added test)
> fix(k8stagger): allow uppercase characters inside tag keys

- .changelog/1401.fixed.txt
- docs/upgrading.md
- pkg/processor/k8sprocessor/README.md
- pkg/processor/k8sprocessor/kube/client_test.go
- pkg/processor/k8sprocessor/kube/kube.go
Fixed #1379 
The previous name was k8s.pod.id.
> fix(k8stagger)!: change default pod id attribute name to k8s.pod.uid

- .github/workflows/release_builds.yml
To avoid duplicate "Build" job
> ci: rename FIPS build job

- .changelog/1408.fixed.txt
- pkg/extension/opampextension/opamp_agent.go
This change is a security fix that prevents other users on the system from being able to read configuration files created as part of OpAMP remote configuration management.
Closes #1386
> Don't allow other users to read config files

- .github/workflows/release_builds.yml
Another change required after upgrading the `upload-artifact` action to `v4`. Since we are now uploading the FIPS binary to a separate artifact, we need to also download it using that separate artifact name.
Related CI failure: https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/7474329473/job/20341159569
> ci: download FIPS binary from separate artifact

- CHANGELOG.md
FIPS capable linux/arm64 binary was added only to dev builds, not the release one. I remove this entry to avoid confusion.
> Update CHANGELOG.md - remove FIPS Capable linux/arm64 binary info

- .changelog/1416.changed.txt
- .github/workflows/release_builds.yml
Updates the release CI job to use the musl toolchain to build FIPS binaries. This should fix an issue where users with older GLIBC versions could not run the FIPS distribution of otelcol-sumo.
A test run can be found on this fork: https://github.com/sensu/sumologic-otel-collector/actions/runs/7468333702/job/20323564335
Running ldd on the resulting binary produces the following output:
```
[root@rhel-7-9 ~]# ldd otelcol-sumo-0.90.1-sumo-10000-fips-linux_amd64 
not a dynamic executable
```
> Use musl toolchain to build static fips release binary

- .github/workflows/release_builds.yml
Artefact name changed in this commit: https://github.com/SumoLogic/sumologic-otel-collector/pull/1416, so we have to use new name to download it (explained here: https://github.com/SumoLogic/sumologic-otel-collector/pull/1416/files#r1448410779)
CI failure: https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/7482929996/job/20377879560
> ci: fix downloading fips binaries

- .changelog/1419.fixed.txt
- .github/workflows/release_builds.yml
While packaging Windows MSI files, the release workflow was mistakenly using the FIPS binary in all cases. This lead to issues for people using the non-FIPS MSI file or the PowerShell installation script, e.g. #1387.
This change makes the workflow grab the right executable in the right case (FIPS vs non-FIPS) and should fix the issue for releases going forward.
> Fix non-FIPS release MSI files

- .changelog/1399.changed.txt
- pkg/extension/opampextension/go.mod
- pkg/extension/opampextension/opamp_agent.go
- pkg/extension/opampextension/opamp_agent_test.go
The sumologic extension may update/alter the API base URL used, following the collector registration process. This base URL redirection is tied to the installation token which the OpAMP extension isn't aware of. Update the OpAMP extension to leverage the sumologic extension's base URL to determine the appropriate OpAMP endpoint (i.e. region).
> Use sumologic extension base URL to determine the appropriate OpAMP endpoint

- .changelog/1422.breaking.txt
- pkg/processor/k8sprocessor/kube/owner.go
- pkg/processor/k8sprocessor/kube/owner_test.go
Use the EndpointSlices resources instead of the Endpoints resource for tracking Pod to Service relationships. This is a newer API which is more efficient - EndpointSlices are smaller, so we don't need to reprocess all of a Service's endpoints whenever one of them changes, which is currently the case.
I've also added a transform function that drops any data we don't use 
This improves memory utilization significantly for large clusters. Aside from unit tests I've also run our Helm Chart integration tests on this change, as well as putting it in our staging environment for a day.
This is a breaking change because it requires new RBAC permissions for k8sprocessor to add Servide metadata.
This is part of the fix for #1414, for now I've added a failing test that is currently skipped.
> feat!(k8sprocessor): use Endpointslices for Service metadata

- .changelog/1426.added.txt
- pkg/processor/k8sprocessor/kube/owner.go
- pkg/processor/k8sprocessor/observability/observability.go
- pkg/processor/k8sprocessor/observability/observability_test.go
Add new and update existing metrics for the k8sprocessor:
* the `other` metrics counting events for non-Pod resources now have a `kind` dimension indicating the resource
* add a `owner_table_size` metric
* add a `service_table_size` for the size of the Pod to Services map
> feat(k8sprocessor): add new owner metrics

- .changelog/1428.fixed.txt
- .changelog/3646.fixed.txt
- pkg/exporter/sumologicexporter/prometheus_formatter.go
- pkg/exporter/sumologicexporter/prometheus_formatter_test.go
we have been sending empty values for all non-string data point attributes, eg:
```
Resource SchemaURL: https://opentelemetry.io/schemas/1.9.0
Resource attributes:
-> status: Int(200)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope otelcol/hostmetricsreceiver/load v0.89.0-sumo-2-23-g86be3
Metric #0
Descriptor:
-> Name: system.cpu.load_average.15m
-> Description: Average CPU Load over 15 minutes.
-> Unit: 1
-> DataType: Gauge
NumberDataPoints #0
Data point attributes:
-> status-c: Int(202)
StartTimestamp: 2024-01-18 03:22:29 +0000 UTC
Timestamp: 2024-01-18 18:51:04.082256952 +0000 UTC
Value: 0.990000
Metric #1
Descriptor:
-> Name: system.cpu.load_average.1m
-> Description: Average CPU Load over 1 minute.
-> Unit: 1
-> DataType: Gauge
NumberDataPoints #0
Data point attributes: …
```
> fix(sumologicexporter): fix prometheus formatter for non-string data point labels

- .changelog/1443.fixed.txt
- otelcolbuilder/.gitignore
- otelcolbuilder/cmd/collector_windows.go
- otelcolbuilder/cmd/main_windows.go.patch
With the introduction of remote management the application command line parameters were modified to include the `--remote-config` startup parameter. However this was unintentionally done only for interactive mode. Since the Windows service initialization code uses a different path the new parameter does not work correctly and the application exits.
The Windows service launch code path from the upstream repository uses the [flags](https://github.com/open-telemetry/opentelemetry-collector/blob/de6287de839a7d2c0273dd1df3a064a08f733904/otelcol/flags.go#L32) function defined in the upstream code, which doesn't support the `--remote-config` command line parameter. For interactive mode that [function was redefined](https://github.com/SumoLogic/sumologic-otel-collector/blob/c9a38b805ab7339fe02e8a0 …
> fix: support --remote-config startup option with Windows services

- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/sender_test.go
See deprecations in [core v0.94.0](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG-API.md#v110v0940).
> refactor(exporter/sumologic): rename deprecated `CompressionType` type

- .changelog/1448.changed.txt
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/owner.go
Log warnings when we're missing data we should have. This usually means the cache is out of sync. Right now we don't have any observability for these kinds of events.
> chore(k8sprocessor): Improve logging of missing data events

- vagrant/windows/README.md
- vagrant/windows/Vagrantfile.common
- vagrant/windows/provision.ps1
- vagrant/windows/windows-server-2012/Vagrantfile
- vagrant/windows/windows-server-2016/Vagrantfile
- vagrant/windows/windows-server-2019/Vagrantfile
- vagrant/windows/windows-server-2022/Vagrantfile
The environments are defined as Vagrantfiles in `vagrant/windows`. They include enough tooling to build Otel and run tests.
Currently missing features I'd like to add in subsequent PRs:
* Docker, including being able to build Windows containers
* More documentation on troubleshooting issues with Otel installed via the install script
* Apple Silicon support of some sort
* More platforms, including at least one non-server version
> chore: Add basic Windows dev environments

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
For some reason dependabot doesn't see the latest microsoft/setup-msbuild release (v2). That's why I update manually
> chore(deps): update microsoft/setup-msbuild to v2 manually

- .changelog/1467.added.txt
- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- Dockerfile_windows
- Makefile
- ci/build-push-multiplatform.sh
- ci/push_docker_multiplatform_manifest.sh
Adds building windows containers. This PR uses docker command in order to build manifest, as for some reason `docker buildx` was not always working, also buildx is not supported on windows
```
➜  ~ docker manifest inspect public.ecr.aws/sumologic/sumologic-otel-collector-dev:latest
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1093,
"digest": "sha256:1fde89d7412f56cac8e295ec067895780d36755c1e0c442e2832024c54b09d4f",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1093,
"digest": "sha256:5815d396401f4f24d69d90c7df4b918c030212719178d368d7d25ccda1b4fbb8", …
```
> feat: build windows containers

- vagrant/windows/README.md
- vagrant/windows/docker/Vagrantfile
Found a turnkey image with Docker for Windows configured, where it's easy to build Windows containers.
> tools(vagrant): add box for building Windows containers

- pkg/scripts_test/check.go
- pkg/scripts_test/check_windows.go
- pkg/scripts_test/command_windows.go
- pkg/scripts_test/common.go
- pkg/scripts_test/common_windows.go
- pkg/scripts_test/config.go
- pkg/scripts_test/consts_windows.go
- pkg/scripts_test/install_windows_test.go
Add some basic Windows install script tests. These basically just check if we end up with the right configuration for a given command line flag set.
The script runner and checks are actually quite similar to unix, and there might be a way to unify them, but that can happen in a followup PR.
> test(install-script): add basic Windows install script tests

- .changelog/1481.added.txt
- pkg/extension/opampextension/go.mod
- pkg/extension/opampextension/go.sum
- pkg/extension/opampextension/opamp_agent.go
```
Upgrade opamp-go to tip
Upgrade to an untagged opamp-go in order to take advantage of the recent
support for HTTP redirection that has been added.
The project has broken several things since 0.10.x, and this breakage
has been reflected as minor changes to the opamp extension as well.
opamp-go should be upgraded to a tagged version on a subsequent release.
```
> Upgrade opamp-go to tip

- .github/workflows/dev_builds.yml
- .github/workflows/workflow-trigger-packaging.yml
In a subsequent PR, I'd like to use this in the release workflow triggered on tags. I've also explicitly set the downstream packaging workflow not to create a draft release.
> ci: add reusable workflow for triggering packaging

- .github/workflows/workflow-trigger-packaging.yml
The workflow used to manually fetch all the tags, leading to an error if it was already triggered for a tag. Instead, do a treeless checkout, which should make things faster in general.
> ci: fix packaging trigger for release builds

- .github/workflows/pull_requests.yml
- Makefile
- ci/build-push-multiplatform.sh
- ci/get_version.sh
- ci/push_docker_multiplatform_manifest.sh
- ci/shellcheck.sh
- scripts/install.sh
* Update shellcheck to the latest 0.10.0
* Run shellcheck on the install script. This was not the case until now, probably by mistake.
* Delete shellcheck.sh and instead explicitly list the files we're checking in the Makefile target.
* Fix some warning and info messages in our scripts.
> chore: fix some shellcheck problems

- vagrant/windows/README.md
For now, just point to UTM. We can provide better instructions once we figure this out.
> docs(vagrant): document Windows dev environment on Apple M1

- .github/workflows/release_builds.yml
The paths in the release workflow were incorrect.
> ci: fix storing install script as artifact

- .github/workflows/dev_builds.yml
- .github/workflows/workflow-trigger-packaging.yml
Our reusable workflow would unconditionally pass the workflow id as the parameter to the triggered packaging workflow.
This causes the packaging workflow to fetch artifacts from the workflow with that id, which is correct for dev builds, but incorrect for release builds. Fix this by making the workflow id an input.
> ci: fix packaging trigger for releases

- .github/workflows/workflow-trigger-packaging.yml
Turns out the workflow run id is considered a string by GHA: https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/8635467376
> ci: fix trigger packaging workflow

- .changelog/1539.fixed.txt
- otelcolbuilder/.otelcol-builder.yaml
The replace was pointing to a directory which didn't exist. Somehow, this didn't break the build.
> fix(build): opampextension replace statement

- .github/workflows/release-packaging.yml
- .github/workflows/release_builds.yml
Packaging for releases should only be triggered after the release is published, as otherwise the packaging workflow can't fetch the artifacts.
> ci: trigger packaging for a release after publishing

- pkg/extension/opampextension/go.mod
- pkg/extension/opampextension/go.sum
opamp-go was previously pinned to an untagged commit
closes #1482
> Upgrade opamp-go to v0.14.0

- scripts/install.ps1
- scripts/install.sh
A recent change deleted the install scripts from this repository. The scripts are still attached to releases, which is how they're supposed to be consumed by users. However, it turns out that some script links in our documentation incorrectly refer to them by their content in `main`.
Restore the scripts until those urls are corrected.
> fix(scripts): restore install scripts temporarily

- .github/workflows/workflow-trigger-packaging.yml
The action we've been using is unmaintained. Triggering the workflow using the github cli is quite easy. It's not as easy to get the workflow url, so I changed the url to point to the workflow list for now.
> ci: use github cli for triggering package workflow

- .github/workflows/workflow-trigger-packaging.yml
github-cli serializes all workflow arguments as strings, so we need to quote all of them.
This fixes failures like the following: https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/8710092270/job/23891784907
> ci: fix trigger packaging argument encoding

- .github/workflows/pull_requests.yml
- .github/workflows/workflow-build.yml
Instead of every job doing its own check for changes to build-relevant files, do the check once and use the result of that check.
> ci: consolidate change detection logic for builds

- Makefile
For release builds, we want to set the right tags for our own modules in the otelcol builder configuration. Currently, this does not work at all, because the sed regex is incorrect.
> chore: fix replacing tags in otelcol builder config for releases

- .github/workflows/release_builds.yml
Minor fix to #1562. There was an unnecessary `v` prefix in a container tag.
> ci: fix typo in release workflow

- .github/workflows/dev_builds.yml
- .github/workflows/workflow-build.yml
This change moves dev builds closer to how release builds are. It consistently sets the same version for the dev build anywhere applicable:
* The application version is now reported as such: 
```
buildinfo:
command: otelcol-sumo
description: *** distribution
version: v0.98.0-sumo-0-6-g3bb36
```
* Internally, our component versions are now set to this value:
```
2024-04-25T11:24:46.172+0200    info    sumologicexporter@v0.98.0-sumo-0-6-g3bb36/exporter.go:88        Sumo Logic Exporter configured  {"kind": "exporter", "data_type": "logs", "name": "sumologic", "log_format": "otlp", "metric_format": "otlp", "trace_format": "otlp"}
```
* Dev container images now use this version as the tag, instead of the commit hash:
```
public.ecr.aws/sumologic/sumologic-otel-collector-dev:0.98.0-sumo-0-6-g3bb …
```
> ci: set version tags for dev build

- examples/otelcolconfigs/README.md
- examples/otelcolconfigs/sampler_configuration_multiple_instances_template.yaml
PR adds example config for multiple cascading filter instances usage.
> chore: add example for cascadingfilter multiple instances

- .changelog/1569.fixed.txt
- pkg/processor/sourceprocessor/source_category_filler.go
- pkg/processor/sourceprocessor/source_category_filler_test.go
- pkg/processor/sourceprocessor/source_processor_test.go
Annotation values which are empty strings should be treated like any other value, and not ignored as if they didn't exist.
> fix(sourceprocessor): don't ignore empty annotation values

- .changelog/1570.fixed.txt
- otelcolbuilder/cmd/collector_windows.go
Bring upstream changes to the windows service
Related issue: https://github.com/open-telemetry/opentelemetry-collector/pull/9516
> fix(windows): Recognize opamp as a config provider

- ci/get_version.sh
This is required to trigger packaging for release candidates, please see below that sumo version was set to `0` but the sumo version was `0-rc.0`
https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/8846781071/job/24293335494
with the fix in this pull request the output will be following:
```
% export VERSION_TAG=v3.99.4-sumo-5-rc.6
% ./get_version.sh sumo                
5-rc.6
% export VERSION_TAG=v3.99.4-sumo-5     
% ./get_version.sh sumo      
5            
```
packaging repository is now prepared for release candidates, please see pull request: https://github.com/SumoLogic/sumologic-otel-collector-packaging/pull/81
> fix(ci): modify getting sumo version to return version with sumo channel

- ci/get_version.sh
Remove version labels/metadata for windows builds
Attempt to include this for windows builds was declined - https://github.com/wixtoolset/issues/issues/6778
> fix(windows): Remove version labels/metadata for windows builds

- .github/workflows/release_builds.yml
Use our shared build workflow for release builds. The only thing that changes from the previous workflows is the artifact names, which don't have the version in them. To keep these consistent, I've added a step to the release job, where it adds the version to the filenames before uploading artifacts to the release.
You can find a release workflow with these changes here: https://github.com/swiatekm-sumo/sumologic-otel-collector/actions/runs/8835198933, and a release here: https://github.com/swiatekm-sumo/sumologic-otel-collector/releases/tag/v0.99.0-sumo-12. One difference between these is that I've disabled docker manifest pushes and binary signing on MacOS and Windows. But all this works in the dev builds anyway.
> ci: use reusable workflow for release builds

- .github/workflows/workflow-build.yml
This will fix CI for dependabot PRs. We do the same thing for MacOS.
See https://github.com/SumoLogic/sumologic-otel-collector/pull/1590 for an example of the failure.
> ci: sign Windows binaries only if certificate is available

- .gitignore
- pkg/tools/otelcol-config/flag_actions.go
- pkg/tools/otelcol-config/opamp.go
- pkg/tools/otelcol-config/opamp_test.go
This commit adds the set-opamp-endpoint action to otelcol-config. The set-opamp-endpoint action sets the OpAmp endpoint in sumologic-remote.yaml. If sumologic-remote.yaml does not exist, then an error is printed. The action also validates that the URL being set has a valid websocket scheme.
> Add --set-opamp-endpoint to otelcol-config

- pkg/tools/otelcol-config/delete_tag.go
- pkg/tools/otelcol-config/delete_tag_test.go
- pkg/tools/otelcol-config/flag_actions.go
This commit adds the delete-tag action to otelcol-config.
The delete-tag action deletes a key out of the collector_fields object in conf.d settings. If the --override flag is provided, then the action deletes the tag out of conf.d overrides.
If a user has manually added a tag to conf.d, and tries to delete it with this tool in override mode, then an error will be returned, and otelcol-config will refuse to proceed.
> Add --delete-tag to otelcol-config

- .changelog/1632.fixed.txt
- otelcolbuilder/cmd/configprovider.go
Add the Default provider to the provider list in ConfigProviderSettings. When the Scheme for a config URI isn't specified, the DefaultScheme is set to the env, therefore this provider now needs to be included in the provider list.
Related to this upstream breaking change - https://github.com/open-telemetry/opentelemetry-collector/pull/10435
> fix(opamp): Add the Default provider to the provider list in ConfigProviderSettings

- pkg/tools/otelcol-config/api_url.go
- pkg/tools/otelcol-config/api_url_test.go
- pkg/tools/otelcol-config/flag.go
- pkg/tools/otelcol-config/flag_actions.go
This commit adds support for the --set-api-url action. It works similarly to the --set-installation-token action.
> Add support for setting base API URL to otelcol-config

- .changelog/1645.fixed.txt
- scripts/install.sh
There's an issue with the script when we hit the github rate limit. When this happens we download an RC if its the most recent release. One could reproduce this by running the old curl command that this PR replaces.
> fix(install): Fix script to always install the latest stable version

- pkg/tools/otelcol-config/conf_loader.go
- pkg/tools/otelcol-config/conf_loader_test.go
This commit fixes a bug in otelcol-config where conf.d does not load properly when a dangling symlink exists.
> otelcol-config: fix a bug in conf.d loading

- pkg/tools/otelcol-config/flag.go
- pkg/tools/otelcol-config/flag_test.go
This commit fixes a bug in otelcol-config, where if --config is not set, the program does not use the expected default of /etc/otelcol-sumo.
> otelcol-config: set a default for --config

- pkg/receiver/jobreceiver/command/command_test.go
Calling t.FailNow or functions that call t.FailNow indirectly from goroutines outside the function under test is not allowed. In this instance, it seems it was causing the test to deadlock.
> Fix a developer error in the jobreceiver tests

- .changelog/1660.fixed.txt
- pkg/receiver/jobreceiver/command/command.go
This commit fixes a concurrency error in the jobreceiver, where the stdin and stderr streams can be read after they are closed, generating spurious errors.
Without this commit applied, the tests in the command package will fail about one time in 30. This can easily be verified:
```
$ go test -count 100
```
After this commit is applied, the tests will always pass even after hundreds of runs.
What this change fixes:
`exec.Cmd.Wait` was being called before the final read to the stdout and stderr readers. This lead to the readers encountering a read-after-close error.
The `exec.Cmd` pipes are eschewed in favour of raw `io.Pipe`s, which are closed outside of `cmd.Wait`. For more information on this technique, see the link below.
https://github.com/golang/go/issues/60309#issuecomment-1555290330
> bugfix: fix a concurrency error in the jobreceiver

- pkg/tools/otelcol-config/add_tag.go
- pkg/tools/otelcol-config/add_tag_test.go
- pkg/tools/otelcol-config/delete_tag.go
- pkg/tools/otelcol-config/delete_tag_test.go
This commit adds support for adding and removing tags when remote control is enabled. This is necessary to bootstrap the connection to the backend, and so must be supported.
> otrm: support tags in otelcol-config

- pkg/tools/otelcol-config/action_context.go
- pkg/tools/otelcol-config/installation_token.go
- pkg/tools/otelcol-config/installation_token_test.go
- pkg/tools/otelcol-config/main.go
When systemd is enabled, we expect tokens to be written to $CONFIGDIR/env/token.env
> otelcol-config: write installation token to env var

- pkg/tools/otelcol-config/main.go
- pkg/tools/otelcol-config/main_unix.go
- pkg/tools/otelcol-config/main_windows.go
This commit makes otelcol-config set the UID and GID of sumologic-remote.yaml to the same UID and GID as sumologic.yaml, when the tool is running with elevated privileges.
If the tool is not running with elevated privileges, then sumologic-remote.yaml will be owned by the user running otelcol-config.
> otelcol-config: chown sumologic-remote.yaml

- pkg/tools/otelcol-config/darwin_test.go
- pkg/tools/otelcol-config/linker_test.go
- pkg/tools/otelcol-config/linux_test.go
- pkg/tools/otelcol-config/main.go
- pkg/tools/otelcol-config/main_unix.go
- pkg/tools/otelcol-config/main_windows.go
- pkg/tools/otelcol-config/smoke_test.go
Correctly set ownership & permissions of configuration files. The owner/group used will match the owner/group of `/etc/otelcol-sumo/sumologic.yaml`. The permissions used is `0600`.
Also fixes the name of the `hostmetrics.yaml` symlink.
> otelcol-config: fix ownership, perms, and hostmetrics filename

- .changelog/1681.fixed.txt
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/owner.go
Removing k8s tagger warnings, as these have been causing false alarms and cost concerns
> fix(k8s_tagger) Removing k8s tagger warnings, as these have been causing false alarms and cost concerns

- .changelog/1678.changed.txt
- .changelog/1681.fixed.txt
- CHANGELOG.md
- releasing v108, ran ```make update-changelog VERSION=0.108.0-sumo-0```
> chore: Prepare release for v0.108.0-sumo-0

- .changelog/1689.added.txt
- pkg/processor/k8sprocessor/README.md
- pkg/processor/k8sprocessor/client_test.go
- pkg/processor/k8sprocessor/config.go
- pkg/processor/k8sprocessor/config_test.go
- pkg/processor/k8sprocessor/factory.go
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
- pkg/processor/k8sprocessor/kube/fake_informer.go
- pkg/processor/k8sprocessor/kube/informer.go
- pkg/processor/k8sprocessor/kube/informer_test.go
- pkg/processor/k8sprocessor/kube/kube.go
- pkg/processor/k8sprocessor/kube/owner.go
- pkg/processor/k8sprocessor/options.go
- pkg/processor/k8sprocessor/processor.go
- pkg/processor/k8sprocessor/processor_test.go
Added pagination when fetching pods from the k8s List API.
Unset the ResourceVersion to get the MostRecent change for an object
https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions
> feat(k8s_tagger): Added pagination when fetching pods from the k8s List API

- pkg/tools/otelcol-config/flag.go
Fixes the default path to the `LaunchDaemons` directory in otelcol-config.
> fix(otelcol-config): fix default LaunchDaemons path

- .github/workflows/workflow-trigger-packaging.yml
Removes the git ref override that was added for testing. I meant to make this change before #1693 was merged.
> chore(ci): remove ref for pkg trigger

- pkg/tools/otelcol-config/remote_control.go
- pkg/tools/otelcol-config/remote_control_test.go
A minimum of one receiver, one exporter, and one pipeline are necessary for otelcol to start. This adds the default pipelines from the default non-remote config but with only a nop receiver & nop exporter.
> fix(otelcol-config): update default remote config

- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_test.go
Version numbers introduced by the new packaging implementation are not supported by the backend when sending collector information. When this new format is recognized clean it up to send a version that is compatible with the backend.
> fix(packaging): cleanup build version number

- pkg/extension/opampextension/components.go
- pkg/extension/opampextension/go.mod
- pkg/extension/opampextension/go.sum
This adds the `nop` exporter and receiver to the list of allowed components used in configurations received through OPAmp. This is necessary because QE has such configurations in their tests and those were reported by the collector as being invalid.
> Add nop components to OPAmp extension

- otelcolbuilder/.otelcol-builder.yaml
- pkg/extension/opampextension/opamp_agent.go
- pkg/extension/opampextension/opamp_agent_test.go
- pkg/tools/otelcol-config/remote_control.go
- pkg/tools/otelcol-config/remote_control_test.go
* Uses new sumologicextension from our fork of opentelemetry-collector-contrib. This is necessary for now as the changes are not available on upstream and upstream is using a newer version of the collector.
* Updated the OpAmp agent to output the filename (includes the source template ID) when processing source templates.
* Added the `file_storage` and `health_check` extensions to the generated `sumologic-remote.yaml` config when using otelcol-config.
> fix(opamp): multiple fixes for opamp

- .changelog/1709.fixed.txt
- examples/sumologic.yaml
- pkg/extension/opampextension/opamp_agent.go
- pkg/tools/otelcol-config/remote_control.go
- pkg/tools/otelcol-config/remote_control_test.go
The OpAmp endpoint with redirection has been moved to a different URL. Updating it.
> fix(opamp): update default opamp endpoint

- otelcolbuilder/.otelcol-builder.yaml
Bumps sumologicextension to the latest commit in our fork which includes a fix for version conversion ƒor fips builds.
> Bump sumologicextension

- .github/workflows/workflow-build-otelcol-config.yml
- .github/workflows/workflow-build.yml
- pkg/tools/otelcol-config/Makefile
The otelcol-config binary is supposed to be built statically but was not due to a bug. This PR fixes the bug along with a few other issues around building / caching otelcol-config that I noticed.
> Build otelcol-config statically

- .changelog/1738.fixed.txt
- otelcolbuilder/.otelcol-builder.yaml
Fix the collector version. Points to this commit - https://github.com/SumoLogic/opentelemetry-collector-contrib/commit/f0c5bb5bac63056954a5387222a776a85696c9c0
> fix(version): Fix the collector version

- CHANGELOG.md
- otelcolbuilder/.otelcol-builder.yaml
New release candidate for 0.118.0-sumo-1
Added the version sanitization commit to v118 - https://github.com/SumoLogic/opentelemetry-collector-contrib/commits/build-number-fix-v0_118
> chore: New release candidate for 0.118.0-sumo-1

- CHANGELOG.md
Removing v0.118.0-sumo-1 from the changelog as we don't need a patch, the version reported in v0.118.0-sumo-0 is correct.
> chore: Removing v0.118.0-sumo-1 from the changelog

- .github/workflows/_get-version-workflow.yml
- .github/workflows/changelog.yaml
- .github/workflows/close-jira-task.yaml
- .github/workflows/create-jira-task.yml
- .github/workflows/dev_builds.yml
- .github/workflows/pr_labeler.yaml
- .github/workflows/pull_requests.yml
- .github/workflows/releases.yml
- .github/workflows/workflow-build-otelcol-config.yml
- .github/workflows/workflow-build.yml
- .github/workflows/workflow-test-otelcol-config.yml
- .github/workflows/workflow-test.yml
- .github/workflows/workflow-trigger-packaging.yml
The Ubuntu 20.04 runners will stop functioning in less than two weeks. These changes pin our runners to Ubuntu 24.04.
> chore(ci): use ubuntu-24.04 runners

- .github/workflows/post-release.yml
As a part of the release process, we used to create tags for each of the exportable packages under the `pkgs` directory. This was lost when we switched to the new release workflow. This PR adds a new `post-release` workflow to reimplement the creation of these tags. It will create and push tags automatically when a release is published. (e.g. draft -> published)
**NOTE** I've done some rudimentary testing but I don't think we can know if this will work until the next release.
> chore(ci): create pkg tags after release publish

- otelcolbuilder/.otelcol-builder.yaml
Fixing collector metadata update issues. The error seen is below
`warn	sumologicextension@v0.124.0/extension.go:913	collector metadata update failed: Error getting executable name: invalid argument	{"collector_name": "prod-www-2105927136.us-east-1.elb.amazonaws.com-1747971493905", "collector_id": "00005AF3107D1233"}`
> fix(sumologic-extension): Fixing collector metadata update issues

- .github/workflows/post-release.yml
Sets the Git user name & email as it is required for the `post-release.yml` workflow. It also adds the `workflow_dispatch` trigger so that we can manually trigger the `post-release.yml` workflow if needed.
> fix(ci): set git user name & email

- pkg/receiver/jobreceiver/go.mod
- pkg/receiver/jobreceiver/output/logentries/config.go
- pkg/receiver/jobreceiver/output/logentries/utf8raw.go
in v0.129.0 contrib release stanza/decode is removed and move to internal package in textutils. as internal package cannot be used outside replicated required method
removing pr: https://github.com/open-telemetry/opentelemetry-collector/pull/13071/files#diff-1c4cd801df522f4a92edbfb0fea95364ed074a391ea47c284ddc078f512f7b6a
Breaking change in 0.129
https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.129.0
textutils: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ff61b386f62d4e26f57d2517264686b1552b7252/internal/coreinternal/textutils/encoding.go#L4
> Removing stanza decode package

- .changelog/1818.changed.txt
- examples/ansible/install_sumologic_otel_collector.yaml
- examples/chef/sumologic-otel-collector/resources/default.rb
- examples/puppet/modules/install_otel_collector/manifests/init.pp
Update Chef,Ansible,Puppet to use cdn url for install script
https://download-otel.sumologic.com/latest/download/install.sh is working fine
> Update Chef,Ansible,Puppet to use cdn url for install script

- .github/workflows/workflow-build-otelcol-config-platform.yml
- .github/workflows/workflow-build-otelcol-platform.yml
- common.mk
- otelcolbuilder/Makefile
- pkg/tools/otelcol-config/Makefile
Fixes #1824.
I've updated the Makefiles & GitHub Workflows to be more resilient to failures.
The following improvements have been made:
* Binary signing is skipped if the binary has already been signed
* DMG file is removed, if it exists, before staging & creating a DMG file
* GitHub Workflow step for signing with retry logic will now exit 1 if all retries failed
* Both otelcol-sumo and otelcol-config now use common targets from `common.mk` for DMG creation, signing, and notarization
> chore: consolidate code signing, fix retry logic

- .changelog/1833.changed.txt
- pkg/extension/opampextension/go.mod
- pkg/extension/opampextension/go.sum
https://nvd.nist.gov/vuln/detail/cve-2025-54388
> chore: Upgrade docker version to address CVE-2025-54388

- .changelog/1861.fixed.txt
- pkg/extension/opampextension/go.mod
- pkg/extension/opampextension/go.sum
Upstream was released on 23rd september after manually reverting to 1.15 version.
after their release, renovatebot upgraded the dependency to 1.16 also on 23rd sept
we made our PR on 24th sept. by that time, since snowflakereceiver go.mod file had been updated to 1.16 for gosnowflake, when go created dependency graph for our build, it used version 1.16 :blob_ohno:
since we know that upstream is releassed with 1.15, i think we can safely create a patch release with 1.15 also.
> deps: downgrading gosnowflake to 1.15.0
