SumoLogic/sumologic-otel-collector

- .github/CODEOWNERS
- .gitignore
- Vagrantfile
- vagrant/README.md
- vagrant/provision.sh
> chore(vagrant): add vagrant environment

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- Dockerfile
- Dockerfile_dev
- Makefile
- ci/build-push-multiplatform.sh
- ci/push_docker_multiplatform_manifest.sh
- otelcolbuilder/Makefile
This PR adds pushing to [Open Source dev ECR](https://gallery.ecr.aws/a4t4y2n3/sumologic-otel-collector-dev) on commits in main and release branches.
Example what it looks like after the push:
Example of successful pipepile ( back then launched on a PR branch not on main):
https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/929478964
> feat(ci): add dev container builds to Dev Builds job on CI

- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/sender_test.go
These tests specify how the `metadata_attributes` configuration works for different formats of logs and metrics.
> test(sumologicexporter): Add tests for `metadata_attributes`

- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
Follows #21
Reason: not fully cherry-picked from: #20
> feat: skip builds for arm

- pkg/extension/sumologicextension/config.go
- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_test.go
- pkg/extension/sumologicextension/factory.go
- pkg/extension/sumologicextension/factory_test.go
Store credentials implementation:
- Check if file with credentials exists on file system
- Read file, and use stored credentials
- Save credentials on collector shutdown
Signed-off-by: Patryk Matyjasek <pmatyjasek@sumologic.com>
> feat: Store credentials implementation

- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/sender.go
> feat: add otlp support for metrics

- README.md
Some links refer to what was introduced in https://github.com/SumoLogic/sumologic-otel-collector/pull/35 so there's a small dependency between those 2 PRs.
> docs: add configuration to main README

- pkg/extension/sumologicextension/authentication.go
- pkg/extension/sumologicextension/credentials.go
- pkg/extension/sumologicextension/extension.go
Refactor collector authentication:
- Create Authentication interface
- Move helper methods to authentication.go file
- Create abstraction for getting collector credentials info
Signed-off-by: Patryk Matyjasek <pmatyjasek@sumologic.com>
> Refactor collector authentication

- .github/workflows/release_builds.yml
Using https://github.com/ncipollo/release-action as this is the one that made globs work when specifying artifacts file names.
> feat(ci): add workflow step for creating github releases

- pkg/extension/sumologicextension/README.md
* collector_name is no longer required
* simplified the collector_name description
* collector_credentials_path changed into collector_credentials_directory
> docs: small fixes - collector_name and creds path

- pkg/exporter/sumologicexporter/exporter_test.go
Sending logs in text format is different to JSON format with regards to metadata treatment, so I propose to keep the attribute translation tests for both JSON and text format (related to #61).
> test(sumologicexporter): Re-add attribute translation tests for logs text format

- otelcolbuilder/.otelcol-builder.yaml
> feat: add fluentforwardreceiver

- pkg/exporter/sumologicexporter/README.md
> docs(sumologicexporter): update README.md

- otelcolbuilder/.otelcol-builder.yaml
> feat: include fix for flushing last log

- pkg/processor/k8sprocessor/factory.go
- pkg/processor/k8sprocessor/options.go
- pkg/processor/k8sprocessor/options_test.go
> feat(k8sprocessor): extract namespace labels

- pkg/processor/sourceprocessor/factory.go
- pkg/processor/sourceprocessor/source_processor.go
- pkg/processor/sourceprocessor/source_processor_test.go
- add support for metrics
- add support for logs
- limit traces support to resource attributes only
> Multiple changes to source processor

- pkg/exporter/sumologicexporter/README.md
> docs(sumologicexporter): add translate_telegraf_attributes to config section

- docs/Installation.md
> docs(installation): add systemd instruction

- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_test.go
> feat(sumologicextension): fail for 4xx errors except 429

- pkg/extension/sumologicextension/extension.go
> feat: log information about being in beta state

- docs/Configuration.md
Adds introductory section to the configuration page, describing how to put all the pieces together.
Also adds the CLI parameters taken from HowToRun.md, which should probably be _decommissioned_.
> docs(configuration): Add introductory section

- README.md
- docs/README.md
> docs: add info about beta state

- docs/README.md
- docs/Upgrade.md
Upgrade is already covered in Installation.md.
> docs: Remove Upgrade.md

- pkg/extension/sumologicextension/README.md
- pkg/extension/sumologicextension/factory.go
> fix(sumologicextension): change default collector url

- pkg/processor/k8sprocessor/README.md
See the individual commits: the first only fixes the formatting; the second one fixes some wording, typos, inconsistencies that I've stumbled upon when going through the docs trying to set up the processor.
The README is still far from perfect, but I hope it's a step in the right direction.
> docs(k8sprocessor): Fix README formatting, typos

- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/translate_attributes.go
- pkg/exporter/sumologicexporter/translate_attributes_test.go
> feat(exporter): translate k8s.service.name to service

- pkg/processor/k8sprocessor/README.md
- pkg/processor/k8sprocessor/client_test.go
- pkg/processor/k8sprocessor/config.go
- pkg/processor/k8sprocessor/config_test.go
- pkg/processor/k8sprocessor/factory.go
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
- pkg/processor/k8sprocessor/kube/kube.go
- pkg/processor/k8sprocessor/options.go
- pkg/processor/k8sprocessor/processor.go
- pkg/processor/k8sprocessor/processor_test.go
> feat(k8sprocessor): expose delimiter to configuration for services

- examples/ansible/README.md
- examples/chef/README.md
- examples/puppet/README.md
> docs: fix link to Configuration, remove unnecessary 'of'

- README.md
- docs/Configuration.md
- otelcolbuilder/.otelcol-builder.yaml
> feat(exporters): add file, carbon and kafka exporters

- pkg/processor/sourceprocessor/source_processor.go
- pkg/processor/sourceprocessor/source_processor_test.go
Due to fluent-bit configuration for sumologic kubernetes collection,
logs from kubernetes with docker log driver are send as json with
`log`, `stream` and `time` keys.
We would like to extract `time` and `stream` to record level attributes
and treat `log` as body of the log
Related issue: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1758
> feat(sourceprocessor): parse out stream, time and log from docker log

- README.md
- otelcolbuilder/.otelcol-builder.yaml
> Include file storage extension

- otelcolbuilder/.otelcol-builder.yaml
Ref: https://github.com/pmalek-sumo/opentelemetry-collector-contrib/commit/11de2c03d3dbbde2e73b8a816318a2515c843985
> feat(filterprocessor): enable log filtering with record level attributes

- pkg/processor/sourceprocessor/README.md
> docs(sourceprocessor): clarify readme about pod annotations

- pkg/processor/sourceprocessor/README.md
> docs(sourceprocessor): describe source host, source name annotations

- docs/Performance.md
Here's a minimal starting point for describing the fine tuning of the collector.
> docs(performance): add fine tuning docs

- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/fields.go
- pkg/exporter/sumologicexporter/fields_test.go
- pkg/exporter/sumologicexporter/sender_test.go
> feat(sumologicexporter): treat empty field as non-existent

- .github/workflows/pull_requests.yml
- .golangci.yaml
Path set as per the [golangci-lint docs](https://golangci-lint.run/usage/configuration/#cache)
> feat(ci): add golangci-lint cache to speed up linting on CI

- docs/KnownIssues.md
add information about issue with missing metadata for Pods with specific names (#334)
> docs: update information about known issues

- .github/workflows/dev_builds.yml
The workflow referenced a non existent step.
> fix(ci): fix dev builds' lint cache

- Makefile
Related slack discussion: https://sumodojo.slack.com/archives/G011R8ZMUEB/p1640018349031800
Related issue: #369
> chore: add makefile targets to manipulate release tags for modules

- pkg/exporter/sumologicexporter/sender.go
Exemplar log entry:
```
2021-12-21T19:07:37.124Z        warn    sumologicexporter@v0.40.0/sender.go:197 There was an issue sending data {"kind": "exporter", "name": "sumologic/containers", "error_id": "1LMGZ-CI8BY-CSDTQ", "message": "X-Sumo-Fields Warning: 1 key-value pairs are dropped as they are exceeding maximum key-value pair number limit 30."}
```
> feat(sumologicexporter): add logs about dropped fields

- pkg/processor/k8sprocessor/kube/owner_test.go
As discovered by @swiatekm-sumo it seems there is an issue with using fake clients with informers: https://github.com/kubernetes/kubernetes/issues/95372
Use the suggested work around from the issue and reenable the asserts in k8sprocessor ownercache tests.
> tests(k8sprocessor): enable asserts in ownercache tests

- pkg/processor/k8sprocessor/kube/owner.go
- pkg/processor/k8sprocessor/kube/owner_test.go
Fixes: https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/2118
> fix(k8sprocessor): add missing daemonset enrichment

- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_test.go
Related to discussion in: https://github.com/SumoLogic/sumologic-otel-collector/pull/404#discussion_r801525739
> refactor(sumologicextension): refactor registration and credentials storage calls

- docs/Configuration.md
Adds configuration examples showing how to configure Filelog receiver to persist position in files between restarts.
> docs(configuration): use File Storage extension with Filelog receiver

- docs/KnownIssues.md
The issue was fixed in https://github.com/SumoLogic/sumologic-otel-collector/pull/354
> docs(known-issues): remove missing metadata issue

- pkg/receiver/telegrafreceiver/README.md
> docs(telegrafreceiver): point docs links to the tagged Telegraf version

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- otelcolbuilder/.gon_config.json
- otelcolbuilder/Makefile
Example of successful CI: https://github.com/SumoLogic/sumologic-otel-collector/runs/5463361566?check_suite_focus=true#step:14:1
> feat(ci): add darwin binary signing and notarization

- Makefile
Accomodate for `gsed` missing and also for tags not starting with `v`
> fix(ci): fix darwin builds

- pkg/processor/k8sprocessor/pod_association.go
- pkg/processor/k8sprocessor/processor_test.go
Backports https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7133.
> feat(k8sprocessor): attempt to parse IP for unknown net.Addr implementations

- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/exporter_test.go
- pkg/exporter/sumologicexporter/factory.go
- pkg/exporter/sumologicexporter/factory_test.go
- pkg/exporter/sumologicexporter/sender_test.go
- pkg/exporter/sumologicexporter/test_data_test.go
Drop metrics attribute used for routing
> feat(exporter/sumologic): drop attribute used by routing processor

- pkg/exporter/sumologicexporter/carbon_formatter_test.go
- pkg/exporter/sumologicexporter/graphite_formatter_test.go
- pkg/exporter/sumologicexporter/prometheus_formatter.go
- pkg/exporter/sumologicexporter/prometheus_formatter_test.go
- pkg/exporter/sumologicexporter/test_data_test.go
Applying the following PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7769
> fix(exporter/sumologic): fix handling empty histograms by prometheus

- pkg/processor/k8sprocessor/README.md
I believe this is much more readable.
There are still things to improve in this description.
> docs(k8sprocessor): describe configuration in yaml

- README.md
> docs: remove beta note

- CHANGELOG.md
- pkg/extension/sumologicextension/README.md
Fixes the description of sumologicextension status
> docs: Clarify status of sumologicextension

- Dockerfile_local
The local Dockerfile was missing some dependencies and builder installation steps.
> chore: fix local Dockerfile

- .github/workflows/release_builds.yml
Update the CI release template to what we're actually using in practice.
> fix(ci): update release template

- docs/Dev.md
Document how to update our patched processors for a new OT core version.
> docs: updating patched processors

- .github/workflows/release_builds.yml
- docs/release.md
> docs(release): improve releasing instructions

- .gitignore
> chore(git): ignore *.log files

- .github/workflows/pull_requests.yml
> chore(github actions): fix plugins-check

- Dockerfile_local
- Makefile
- vagrant/README.md
- vagrant/provision.sh
> docs(vagrant): improve vagrant documentation

- CHANGELOG.md
> chore: prepare release v0.53.0-sumo-0

- .github/workflows/release_builds.yml
- CHANGELOG.md
> ci: comment out references to MacOS build

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
changed-files steps is used only in pipelines for pull requests
> fix(ci): remove wrong if condition in pipelines for FIPS binaries

- docs/release.md
- otelcolbuilder/.otelcol-builder.yaml
The fingerprint size change bug has been fixed in upstream.
> chore: remove fork of stanza

- .github/workflows/dev_builds.yml
- .github/workflows/release_builds.yml
- pkg/receiver/rawk8seventsreceiver/receiver_test.go
- [chore(ci): add suffix to latest tag for images with FIPS binaries](https://github.com/SumoLogic/sumologic-otel-collector/commit/6d23d561d596a04ea0668faa34585d391be777e0)
- [fix(ci): change target used to build FIPS images in dev builds](https://github.com/SumoLogic/sumologic-otel-collector/commit/597a336e20e9691aafaf5ab1395d4559f1c8e023)
> ci: fixes in dev pipeline for FIPS images

- .github/workflows/release_builds.yml
- CHANGELOG.md
The notarization process is said to be fixed.
> ci: re-enable MacOS builds

- .github/workflows/release_builds.yml
- otelcolbuilder/.gon_config_amd64_fips.json
- otelcolbuilder/.gon_config_arm64_fips.json
- otelcolbuilder/Makefile
- fix(ci): add configurations for signing FIPS binaries
- chore(ci): remove unnecessary steps - download of binaries and checking files
> Fixes in release pipeline

- otelcolbuilder/.otelcol-builder.yaml
> fix: fix deprecation warning

- pkg/processor/k8sprocessor/pod_association.go
- pkg/processor/k8sprocessor/processor.go
Fixes #238
This PR adds some debug logs in the k8s processor.
> chore(k8sprocessor): add debug logs

- docs/release.md
> docs(release): update release instruction with milestone tasks

- CHANGELOG.md
> chore: release v0.56.0-sumo-0

- CHANGELOG.md
> chore: post-release

- README.md
> docs(readme): add a table with supported OS and architectures

- docs/Configuration.md
- docs/Installation.md
- pkg/extension/sumologicextension/README.md
> docs(sumologicextension): add information about running the collector as systemd service

- CHANGELOG.md
- docs/Upgrading.md
This commit updates the changelog and the upgrading guide.
> chore: prepare for release v0.57.2-sumo-0

- CHANGELOG.md
- docs/release.md
- otelcolbuilder/.otelcol-builder.yaml
Removes support for expr language
deprecated in [v0.55.0](https://github.com/SumoLogic/sumologic-otel-collector/blob/main/CHANGELOG.md#v0550-sumo-0)
> feat: drop support for expr in filterprocessor

- CHANGELOG.md
- pkg/processor/k8sprocessor/kube/client.go
- pkg/processor/k8sprocessor/kube/client_test.go
> fix(k8sprocessor): fix metadata enrichment

- scripts/install.sh
Sorry for big PR. This is incorporating the following changes:
* arguments support
* stop supporting version as env, add it as argument
* generating default configuration
* support for install token as env and argument
* fail if link to binary is incorrect
> chore: add default template generation

- scripts/install.sh
> chore(scripts/install): fix systemd check

- .github/workflows/pull_requests.yml
- pkg/scripts_test/Makefile
- pkg/scripts_test/go.mod
- pkg/scripts_test/go.sum
- pkg/scripts_test/install_test.go
- scripts/install.sh
> test: init install script tests

- scripts/install.sh
We do not want our customers to change config or data directories during installation
> feat(scripts/install.sh): remove unwanted arguments

- examples/sumologic.yaml
> feat(scripts/install.sh): rename FILE_STORAGE to SUMOLOGIC_FILE_STORAGE

- scripts/install.sh
> feat(scripts/install.sh): update default configuration links

- docs/Installation.md
- pkg/scripts_test/check.go
- pkg/scripts_test/install_test.go
- scripts/install.sh
> docs(installation): document install script features

- docs/Installation.md
- examples/ansible/install_sumologic_otel_collector.yaml
- examples/ansible/templates/systemd_service.j2
- examples/chef/sumologic-otel-collector/resources/default.rb
- examples/puppet/modules/install_otel_collector/files/systemd_service
- examples/puppet/modules/install_otel_collector/manifests/init.pp
- examples/systemd/otelcol-sumo.service
- scripts/install.sh
> docs(scripts/install.sh): use otelcol-sumo as default user

- scripts/install.sh
> feat(scripts/install.sh): update links to configuration

- .github/workflows/pull_requests.yml
- .markdownlint/style.json
- .markdownlint/style.rb
- docs/Upgrading.md
> docs(upgrading): fix lint

- examples/sumologic.yaml
> fix: fix default configuration

- scripts/install.sh
Add option to specify branch/commit to get configuration from
> feat(scripts/install.sh): add --config-branch option

- scripts/install.sh
> feat(scripts/install.sh): add --binary-branch option

- scripts/install.sh
> fix(scripts_test): use /var/lib/otelcol-sumo as home directory

- scripts/install.sh
> fix(scripts_test): fix sed for bash3

- examples/sumologic.yaml
> feat(examples/sumologic.yaml): add sumologic_schema processor

- scripts/install.sh
> feat(scripts/install.sh): restart systemd service after upgrade

- CHANGELOG.md
> docs(changelog): update according to release v0.57.2-sumo-1

- pkg/configprovider/globprovider/provider.go
- pkg/configprovider/globprovider/provider_test.go
> fix(globprovider): don't error on empty globs

- CHANGELOG.md
- docs/release.md
- otelcolbuilder/.otelcol-builder.yaml
This reverts commit 071e5be159ff592dd3e512780986392896417abf.
> fix(build): revert "feat(build): use patched versions of four upstream receivers"

- docs/troubleshooting.md
Here's a minimal set of troubleshooting docs I came up with. We can always add more as we (or other users) hit issues installing the collector.
> docs: add installation troubleshooting

- CHANGELOG.md
Some entries were missing links to the corresponding PR.
> docs(changelog): add missing PR links

- scripts/install.sh
If SELinux is enabled, we need to do a bit more work to get our systemd service to run.
I've also done a bit of cleanup, in particular to make purge work if there's something wrong with systemd.
> fix(scripts/install.sh) add SELinux labels

- CHANGELOG.md
- docs/upgrading.md
- otelcolbuilder/cmd/configprovider.go
> feat(receiver/elasticsearch)!: enable feature gates by default

- CHANGELOG.md
- pkg/extension/sumologicextension/config.go
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/6851
> feat(extension/sumologic): mark `install_token` as opaque

- CHANGELOG.md
> fixed minor changelog typo for 0.69.0

- scripts/install.sh
Storing temporary files in `/tmp/` in general is unsafe. A malicious user can prepare files there and make us install their own binary. We've also been putting backups of config files in the working directory, which can leak secrets.
To prevent this, use a safe directory for temporary files. 
As we have a feature that can keep downloaded binaries after installation, I put those in `/var/cache/otelcol-sumo`, which is a standard location for system caches, and only writable by root.
> fix(scripts/install.sh): use a safe dir for temp files

- ci/build-push-multiplatform.sh
- ci/push_docker_multiplatform_manifest.sh
Working run: https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/4085445456
Tested locally and pulling both images works for amd64 (both fips and normal, tested with `docker pull public.ecr.aws/sumologic/sumologic-otel-collector-dev:70c26f6906b46795a0850d42c3e9848e7af32920`)
> fix(ci): fix failing devbuilds

- otelcolbuilder/cmd/configprovider.go
> chore(build): don't set elasticsearch receiver feature flags

- .github/workflows/release_builds.yml
Signs the produced Windows binary (`.exe`) and MSI package.
I used the Sensu fork to test the changes to the github action. I have already added the necessary secrets to this repository.
> Sign the collector's Windows binary and MSI package

- scripts/install.sh
> feat(scripts/install): use sed instead of xargs

- examples/sumologic.yaml
> feat(sumologic.yaml): expose prometheus metrics on localhost

- scripts/install.sh
Make output more readable by replacing changelog with link to it
> feat(scripts/install.sh): show link to changelog instead of full changelog

- CHANGELOG.md
- pkg/exporter/sumologicexporter/README.md
- pkg/extension/opampextension/README.md
- pkg/extension/sumologicextension/README.md
- pkg/extension/sumologicextension/config.go
- pkg/extension/sumologicextension/extension.go
- pkg/extension/sumologicextension/extension_test.go
- pkg/extension/sumologicextension/factory_test.go
- pkg/extension/sumologicextension/testdata/config.yaml
> feat(sumologicextension): deprecate install_token in favor of installation_token

- scripts/install.sh
```
Installed version:      0.47.0-sumo-0
Getting versions...
Version to install:     0.71.0-sumo-0
The following versions contain breaking changes: v0.49.0-sumo-0, v0.51.0-sumo-0, v0.52.0-sumo-0, v0.66.0-sumo-0, v0.71.0-sumo-0! Please make sure to read the linked Changelog file.
Changelog:              https://github.com/SumoLogic/sumologic-otel-collector/blob/v0.71.0-sumo-0/CHANGELOG.md
Downloading:            https://github.com/SumoLogic/sumologic-otel-collector/releases/download/v0.71.0-sumo-0/otelcol-sumo-0.71.0-sumo-0-linux_amd64
```
> feat(scripts/install.sh): print info about breaking changes

- CHANGELOG.md
- pkg/exporter/syslogexporter/README.md
- pkg/exporter/syslogexporter/config.go
- pkg/exporter/syslogexporter/examples/config_with_token.yaml
- pkg/exporter/syslogexporter/factory_test.go
- pkg/exporter/syslogexporter/syslog.go
- pkg/exporter/syslogexporter/syslog_test.go
Token which is required by Cloud Syslog Source can be added by logtransform procesor
> feat(syslogexporter): remove adding additional structure data in syslog exporter

- CHANGELOG.md
- pkg/exporter/syslogexporter/README.md
- pkg/exporter/syslogexporter/config.go
- pkg/exporter/syslogexporter/examples/config.yaml
- pkg/exporter/syslogexporter/examples/config_with_token.yaml
- pkg/exporter/syslogexporter/exporter.go
feat(syslogexporter): add mTLS support
feat(syslogexporter): enable using localhost as endpoint in configuration
fix(changelog): move changes added in #975 to unreleased section
> feat(syslogexporter): add mTLS support

- docs/installation.md
Add information how to use environmental variables in systemd
> docs: add information how to use environmental variables in systemd

- CHANGELOG.md
- pkg/exporter/syslogexporter/README.md
- pkg/exporter/syslogexporter/config.go
- pkg/exporter/syslogexporter/examples/config.yaml
- pkg/exporter/syslogexporter/examples/config_with_token.yaml
- pkg/exporter/syslogexporter/exporter.go
- pkg/exporter/syslogexporter/factory_test.go
This allows using self-signed certificates
> feat(syslogexporter): add option to skip certificate verfication

- pkg/exporter/syslogexporter/exporter.go
- pkg/exporter/syslogexporter/syslog.go
chore(syslogexporter): remove not used fields from structs: hostname, pid, app
> chore(syslogexporter): remove not used fields from structs

- pkg/exporter/syslogexporter/config.go
- pkg/exporter/syslogexporter/config_test.go
- pkg/exporter/syslogexporter/deduplicate_errors.go
- pkg/exporter/syslogexporter/exporter.go
- pkg/exporter/syslogexporter/utils.go
- pkg/exporter/syslogexporter/utils_test.go
fix(syslogexporter): validate all inputs at once and add display all error messages
> fix(syslogexporter): validate all inputs at once and add display all error messages

- otelcolbuilder/Makefile
https://pkg.go.dev/net#hdr-Name_Resolution
> chore: use go dns for all binaries

- .github/workflows/dev_builds.yml
Fixes building fips dev image after #1011
> fix(ci): use build-push-container-multiplatform-dev for fips

- CHANGELOG.md
- README.md
- otelcolbuilder/.otelcol-builder.yaml
note: Please review commit by commit. It would be easier
> feat: add missing OpenTelemetry components

- .github/workflows/release_builds.yml
Implements https://github.com/SumoLogic/sumologic-otel-collector/pull/974 for release build
> chore: fix windows release build

- docs/comparison.md
https://github.com/SumoLogic/sumologic-otel-collector/blob/otel-windows-support-doc/docs/comparison.md
> doc(comparison.md): OTEL now has windows support

- pkg/exporter/syslogexporter/config.go
- pkg/exporter/syslogexporter/config_test.go
- pkg/exporter/syslogexporter/exporter.go
- pkg/exporter/syslogexporter/exporter_test.go
- pkg/exporter/syslogexporter/factory.go
- pkg/exporter/syslogexporter/factory_test.go
- pkg/exporter/syslogexporter/syslog.go
- pkg/exporter/syslogexporter/syslog_test.go
- pkg/exporter/syslogexporter/utils.go
- pkg/exporter/syslogexporter/utils_test.go
- chore(syslogexporter): add missing license headers
- chore(syslogexporter): change order of imports
> chore(syslogexporter): add license headers & change order of imports

- docs/migration.md
One nit: in original [Sumo doc](https://help.sumologic.com/docs/send-data/installed-collectors/sources/docker-sources/) there are some mentions about features that now can be achieved with otelcol processors such as `filter` and `source`, but I guess this is so common that we already have it documented elsewhere.
> docs(migration): update info about docker stats source

- docs/migration.md
migration doc edits for syslog source
> docs(syslog): migration doc edits for syslog source

- docs/migration.md
> docs(migration): update info about local windows event source

- docs/migration.md
Based on https://help.sumologic.com/docs/send-data/use-json-configure-sources/#common-parameters-for-log-source-types
> docs(migration): update common parameters for local config file

- Makefile
- docs/best-practices.md
- docs/configuration.md
- docs/fips.md
- docs/installation.md
- docs/known-issues.md
- docs/migration.md
- docs/release.md
- docs/troubleshooting.md
- docs/upstream-relation.md
Update the versions after the latest release. 
Also add a make target to do this automatically.
> docs: update otel version to latest

- .github/dependabot.yml
- .github/workflows/changelog.yaml
This is to be compatible with https://github.com/SumoLogic/sumologic-kubernetes-collection
> chore: use `skip-changelog` label instead of `Skip Changelog`

- CHANGELOG.md
- README.md
- otelcolbuilder/.otelcol-builder.yaml
Fixed some issues with the README as well.
> fix: add lokireceiver back after accidental removal

- CHANGELOG.md
- docs/upgrading.md
- otelcolbuilder/cmd/configprovider.go
See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21743 for more context.
> feat!: disable Prometheus metrics name normalization by default

- CHANGELOG.md
The release failed due to a MacOS signing problem. We'll retry the release after the issue is fixed.
> docs: revert release v0.78.0-sumo-0

- pkg/exporter/sumologicexporter/README.md
ref: https://github.com/open-telemetry/opentelemetry-collector/blob/v0.78.2/exporter/exporterhelper/queued_retry.go#L26
> docs(exporter/sumologic): update default value for queue_size

- CHANGELOG.md
- pkg/exporter/sumologicexporter/sender.go
- pkg/exporter/sumologicexporter/sender_test.go
> fix(sumologicexporter): don't send empty attributes

- pkg/extension/sumologicextension/extension.go
We have some flaky e2e tests, but we do not know why collector metadata update is failing:
```
[54.241.207.187] out: 2023-07-11T13:01:04.383Z	info	extensions/extensions.go:30	Starting extensions...
[54.241.207.187] out: 2023-07-11T13:01:04.383Z	info	extensions/extensions.go:33	Extension is starting...	{"kind": "extension", "name": "sumologic/otc"}
[54.241.207.187] out: 2023-07-11T13:01:04.383Z	info	sumologicextension@v0.77.0-sumo-0/extension.go:364	Locally stored credentials not found, registering the collector	{"kind": "extension", "name": "sumologic/otc"}
[54.241.207.187] out: 2023-07-11T13:01:04.385Z	info	sumologicextension@v0.77.0-sumo-0/extension.go:452	Calling register API	{"kind": "extension", "name": "sumologic/otc", "URL": "https://*/api/v1/collector/register"}
[54.241.207.187] …
```
> chore(sumologicextenstion): log metadata update errors

- CHANGELOG.md
- scripts/install.sh
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20435
> feat(install.sh): prevent permission error when collecting host metrics

- pkg/processor/cascadingfilterprocessor/README.md
> fix main options names for accept and reject policies

- .changelog/1332.changed.txt
- pkg/exporter/sumologicexporter/README.md
- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/factory_test.go
Increasing the default timeout in the sumologic exporter
> Increasing the default timeout in the sumologic exporter

- .changelog/1340.changed.txt
- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- .github/workflows/workflow-build.yml
- .github/workflows/workflow-test.yml
- Dockerfile_local
- vagrant/provision.sh
This is currently the latest in `v1.20` branch.
> chore: update Go to `v1.20.11`

- .changelog/1389.fixed.txt
- pkg/processor/sourceprocessor/attribute_filler.go
- pkg/processor/sourceprocessor/source_processor_test.go
Fixes https://github.com/SumoLogic/sumologic-otel-collector/issues/1322#issuecomment-1854385589
> Support / in source category template attribute

- pkg/exporter/sumologicexporter/README.md
https://github.com/SumoLogic/sumologic-otel-collector/blob/12a171a43cd7506df42e356b9e449124ce01655f/pkg/exporter/sumologicexporter/config.go#L65
> docs(sumologicexporter): document client option

- docs/comparison.md
We now have OTEL Collector  API public 
https://api.au.sumologic.com/docs/#tag/otCollectorManagementExternal
> Update docs for OTEL Collector API

- pkg/exporter/sumologicexporter/sender_test.go
Add a test for zlib compressed data, as in our documentation
https://help.sumologic.com/docs/send-data/hosted-collectors/http-source/logs-metrics/#compressed-data
> Add a test for zlib compressed data, as in our documentation

- docs/comparison.md
- docs/configuration.md
- examples/otelcolconfigs/config_logging.yaml
- examples/otelcolconfigs/logs_json/config.yaml
- examples/otelcolconfigs/verify_installation.yaml
- pkg/extension/sumologicextension/testdata/config.yaml
- pkg/receiver/activedirectoryinvreceiver/README.md
- pkg/receiver/jobreceiver/testdata/usage.yaml
> docs: replace deprecated Logging exporter with Debug exporter

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- ci/build-push-multiplatform.sh
- ci/push_docker_multiplatform_manifest.sh
ref: https://github.com/SumoLogic/sumologic-otel-collector/pull/1440#issuecomment-1935412508
> chore(ci): rename LATEST_TAG_FIPS_SUFFIX variable to BUILD_TYPE_SUFFIX

- .changelog/1448.changed.txt
- .changelog/1452.breaking.txt
- .changelog/1453.fixed.txt
- .changelog/1455.breaking.txt
- CHANGELOG.md
Preparing changelog for new build 0.94.0-sumo-1
> chore: Preparing changelog for new build 0.94.0-sumo-1

- scripts/install.sh
I've had some reports of the Mac install succeeding despite otelcol itself failing. I've tweaked the failure detection to be more precise and increased the timeout to 15s. This appears to fix the problem in all cases I'm aware of, but we should keep an eye on it - maybe even abandon this detection entirely or do a different kind of check?
> fix(scripts/install.sh): improve install failure detection

- .changelog/1471.added.txt
- pkg/processor/sourceprocessor/README.md
- pkg/processor/sourceprocessor/attribute_filler.go
- pkg/processor/sourceprocessor/config.go
- pkg/processor/sourceprocessor/config_test.go
- pkg/processor/sourceprocessor/factory.go
- pkg/processor/sourceprocessor/source_category_filler.go
- pkg/processor/sourceprocessor/source_category_filler_test.go
- pkg/processor/sourceprocessor/source_processor.go
- pkg/processor/sourceprocessor/source_processor_test.go
- pkg/processor/sourceprocessor/testdata/config.yaml
feat: use namespace annotations to include/exclude namespace from collection or set sourceCategory, sourceHost, and sourceName
> feat: use namespace annotations

- pkg/scripts_test/Makefile
- pkg/scripts_test/check_windows.go
- pkg/scripts_test/consts_windows.go
- pkg/scripts_test/go.mod
- pkg/scripts_test/go.sum
- pkg/scripts_test/install_windows_test.go
Check file ownership and permissions in Windows install script tests.
> test(scripts/install.ps1): check file ownership and permissions

- .github/workflows/release_builds.yml
related release build failure: https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/8251637581/job/22608922735
> fix(ci): add missing backslashes in release workflow

- .github/workflows/dev_builds.yml
- .github/workflows/workflow-trigger-packaging.yml
Remote build triggered from this one: https://github.com/SumoLogic/sumologic-otel-collector-packaging/actions/runs/8269980967
> ci: fix trigger packaging workflow

- .changelog/1510.fixed.txt
- Dockerfile_ubi
Set execution bit manually for ubi images
> fix: fix UBI docker image

- .github/workflows/release_builds.yml
- docs/release.md
Automatically trigger the packaging workflow for release builds.
> ci: trigger packaging for release builds

- .changelog/1510.fixed.txt
- Dockerfile_ubi
Reverts SumoLogic/sumologic-otel-collector#1510
> Revert "fix: fix UBI docker image"

- .changelog/1509.added.txt
- .changelog/1512.fixed.txt
- CHANGELOG.md
prepare release v0.96.0-sumo-1
> prepare release v0.96.0-sumo-1

- pkg/scripts_test/check_windows.go
- pkg/scripts_test/install_windows_test.go
- scripts/install.ps1
I've made the script treat package versions and application versions separately and added a test for installing the fips package.
> feat(scripts/install.ps1): use msi packages from the packaging repo

- .changelog/1539.fixed.txt
- .changelog/1540.fixed.txt
- CHANGELOG.md
I'm just going to do it on the main branch, since we had no changes we don't want included.
> chore: prepare release 0.97.0-sumo-1

- .changelog/1549.added.txt
- .github/workflows/dev_builds.yml
- .github/workflows/release_builds.yml
- docs/installation.md
It's working for dev repository:
- https://hub.docker.com/repository/docker/sumologic/sumologic-otel-collector-dev/tags
- https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/8724529923
> feat: push images to dockerhub

- .changelog/1538.changed.txt
- .changelog/1547.added.txt
- .changelog/1549.added.txt
- CHANGELOG.md
- Makefile
chore: prepare release 0.98.0-sumo-0
> chore: prepare release 0.98.0-sumo-0

- otelcolbuilder/cmd/configprovider.go
chore: remove unused function - makeMapProvidersMap
related CI failure: https://github.com/SumoLogic/sumologic-otel-collector/actions/runs/8831884519/job/24248031908
> chore: remove unused function - makeMapProvidersMap

- .changelog/1553.changed.txt
- .github/workflows/pull_requests.yml
- scripts/install.ps1
- scripts/install.sh
Reverts SumoLogic/sumologic-otel-collector#1553. As per https://github.com/SumoLogic/sumologic-otel-collector/issues/1571, we missed urls in the puppet/chef/ansible modules. I'll fix these in a follow-up. We'll need to keep the scripts around in `main` for a bit longer though, it looks like.
> Revert "chore: remove install scripts"

- .changelog/1581.fixed.txt
- examples/ansible/install_sumologic_otel_collector.yaml
- examples/chef/sumologic-otel-collector/resources/default.rb
- examples/puppet/modules/install_otel_collector/manifests/init.pp
> fix: use the right install script url in orchestrator modules

- .changelog/1560.changed.txt
- .changelog/1569.fixed.txt
- .changelog/1570.fixed.txt
- .changelog/1581.fixed.txt
- CHANGELOG.md
> chore: prepare release 0.99.0-sumo-0

- CONTRIBUTING.md
Link `release.md` in `CONTRIBUTING.md`
> docs: link release.md in CONTRIBUTING.md

- .github/workflows/close-jira-task.yaml
Tested on Sumo Logic Kubernetes Collection
> chore: close jira if issue is closed

- examples/sumologic-windows.yaml
- examples/sumologic.yaml
- otelcolbuilder/.otelcol-builder.yaml
- packaging/msi/SumoLogic.wixext/SumoLogicTests/TestData/with-extensions-block.yaml
- pkg/exporter/sumologicexporter/config.go
- pkg/exporter/sumologicexporter/exporter.go
- pkg/exporter/sumologicexporter/go.mod
- pkg/exporter/sumologicexporter/go.sum
- pkg/extension/opampextension/components.go
- pkg/extension/opampextension/config.go
- pkg/extension/opampextension/config_test.go
- pkg/extension/opampextension/factory_test.go
- pkg/extension/opampextension/go.mod
- pkg/extension/opampextension/go.sum
- pkg/extension/opampextension/opamp_agent.go
- pkg/extension/sumologicextension/README.md
Deprecate Sumo Logic Extension in favor of upstream ones
> feat(sumologicextension): deprecate in favor of OpenTelemetry Contrib extension

- .changelog/1594.changed.txt
- .github/workflows/dev_builds.yml
- .github/workflows/release_builds.yml
- Dockerfile_ubi
It would help me with testing OpenShift release as I'm using M2 😞
> feat: build UBI image for arm64

- .changelog/1614.added.txt
- pkg/extension/opampextension/components.go
- pkg/extension/opampextension/go.mod
- pkg/extension/opampextension/go.sum
- pkg/extension/opampextension/opamp_agent_test.go
- pkg/extension/opampextension/testdata/opamp.d/opamp-kafkametrics-config.yaml
> feat(opamp): Validate kafkametricsreceiver

- .changelog/1600.added.txt
- .changelog/1601.changed.txt
- .changelog/1605.added.txt
- .changelog/1611.changed.txt
- .changelog/1614.added.txt
- .changelog/1619.changed.txt
- .changelog/1632.fixed.txt
- .changelog/1645.fixed.txt
- CHANGELOG.md
Prepare release 0.104.0-sumo-0
> chore: Prepare release 0.104.0-sumo-0

- pkg/tools/otelcol-config/main_unix.go
- pkg/tools/otelcol-config/main_windows.go
Previous commit was broken but CI was not gating automerge.
> otelcol-config: fix windows build

- .changelog/1657.added.txt
- .changelog/1660.fixed.txt
- .changelog/1662.2.changed.txt
- .changelog/1662.changed.txt
- .changelog/1674.added.txt
- CHANGELOG.md
> (docs): Added changelog for v0.106.1-sumo-0

- .changelog/1674.added.txt
- CHANGELOG.md
- Prepare release for v0.106.1-sumo-1
> chore: Prepare release for v0.106.1-sumo-1 

- pkg/tools/otelcol-config/main.go
Applies the same ownership & permissions fixes implemented in #1676 but for the `00-otelcol-config-settings.yaml` and `99-otelcol-config-overrides.yaml` files.
> otelcol-config: fix ownership & perms for confd files

- .github/workflows/dev_builds.yml
- .github/workflows/pull_requests.yml
- .github/workflows/release_builds.yml
- .github/workflows/workflow-trigger-packaging.yml
This helps when tracing the linkage between this repository and sumologic-otel-collector-packaging.
> Output the "Trigger Packaging" workflow ID

- .github/workflows/workflow-trigger-packaging.yml
Change to CI annotations only.
> Fix variable expansion

- .changelog/1689.added.txt
- CHANGELOG.md
Prepare release 0.108.0-sumo-1
> chore: Prepare release 0.108.0-sumo-1

- .changelog/1721.added.txt
- pkg/extension/opampextension/components.go
- pkg/extension/opampextension/go.mod
- pkg/extension/opampextension/go.sum
- pkg/extension/opampextension/opamp_agent_test.go
- pkg/extension/opampextension/testdata/opamp.d/opamp-attributes-processor.yaml
Add validation for the attributes processor
> feat: Add validation for the attributes processor

- .github/workflows/workflow-build.yml
- .github/workflows/workflow-test.yml
- otelcolbuilder/Makefile
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>
> Require yq in Makefile, install yq on Windows CI runners

- .changelog/1604.changed.txt
- .changelog/1693.changed.txt
- .changelog/1709.fixed.txt
- .changelog/1714.changed.txt
- .changelog/1721.added.txt
- CHANGELOG.md
> chore: Update Changelog 0.114.0

- otelcolbuilder/.otelcol-builder.yaml
Updates the dependency on our fork of the sumologicextension to pull in the 0.114.0 changes.
> chore: update sumologicextension fork

- CHANGELOG.md
- otelcolbuilder/.otelcol-builder.yaml
New release candidate for 0.118.0-sumo-1
> chore: New release candidate for 0.118.0-sumo-1

- .idea/.gitignore
- pkg/tools/otelcol-config/flag.go
- pkg/tools/otelcol-config/flag_actions.go
- pkg/tools/otelcol-config/flag_test.go
- pkg/tools/otelcol-config/remote_control.go
- pkg/tools/otelcol-config/remote_control_test.go
- pkg/tools/otelcol-config/smoke_test.go
- pkg/tools/otelcol-config/timezone.go
- pkg/tools/otelcol-config/timezone_test.go
Add support to timezone so that we can use it in add collector workflow
> otelcol-config: add timezone support

- docs/migration.md
OTC collector is supported in ingest budget
https://help.sumologic.com/docs/manage/ingestion-volume/ingest-budgets/
> Update migration.md for ingest budget

- .changelog/1807.added.txt
- pkg/extension/opampextension/README.md
Added a table in opampextension/README.md to reflect the components which are added to the extension.
> docs: Updated readme file to reflect the components for opampextension

- .changelog/1808.changed.txt
- pkg/extension/opampextension/README.md
Mum deployment is now decommissioned and KOR is new deploy
> docs: removed IN and added KR deployment in opampextension README.md

- .github/workflows/renovate-scheduler.yml
- renovate.json5
fixed the renovate config, removed schedule.
> Astitva reno fix

- .changelog/1803.added.txt
- .changelog/1804.added.txt
- .changelog/1806.added.txt
- .changelog/1807.added.txt
- .changelog/1808.changed.txt
- .changelog/1812.added.txt
- .changelog/1813.added.txt
- .changelog/1816.changed.txt
- .changelog/1818.changed.txt
- .changelog/1822.changed.txt
- .changelog/1833.changed.txt
- .changelog/1834.added.txt
- .changelog/1834.changed.txt
- .changelog/1840.changed.txt
- CHANGELOG.md
consolidate changelogs for 133 release
> chore:0.133.0 change logs

- .changelog/1848.changed.txt
- examples/puppet/modules/install_otel_collector/manifests/init.pp
> Puppet remote support for windows
